import { writable } from 'svelte/store';

export type LanguageCode = 'en' | 'es' | 'pt';

export interface LanguageOption {
    code: LanguageCode;
}

export const LANGUAGES: LanguageOption[] = [
    { code: 'en' },
    { code: 'es' },
    { code: 'pt' }
];

const MESSAGES = {
    en: {
        'nav.discover': 'Discover',
        'nav.matches': 'Matches',
        'nav.profile': 'Profile',
        'language.en': 'English',
        'language.es': 'Spanish',
        'language.pt': 'Portuguese',
        'common.all': 'All',
        'common.any': 'Any',
        'common.yes': 'Yes',
        'common.no': 'No',
        'common.search': 'Search',
        'common.noResults': 'No results',
        'common.showMore': 'More +',
        'common.save': 'Save',
        'common.saving': 'Saving...',
        'common.refresh': 'Refresh',
        'common.close': 'Close',
        'common.cancel': 'Cancel',
        'common.clear': 'Clear',
        'common.keepSwiping': 'Keep swiping',
        'common.information': 'Information',
        'common.removeSport': 'Remove',
        'common.continue': 'Continue',
        'common.letsGo': "Let's go!",
        'common.like': 'Like',
        'common.pass': 'Pass',
        'common.undo': 'Undo',
        'common.message': 'Message',
        'common.gotIt': 'Got it',
        'common.maybeLater': 'Maybe later',
        'common.back': 'Back',
        'common.loading': 'Loading...',
        'common.chat': 'Chat',
        'common.match': 'Match',
        'common.new': 'New',
        'common.format': 'Format',
        'common.level': 'Level',
        'common.gender': 'Gender',
        'common.orientation': 'Orientation',
        'common.name': 'Name',
        'common.email': 'Email',
        'common.biography': 'Biography',
        'common.location': 'Location',
        'common.sports': 'Sports',
        'common.mySports': 'My Sports',
        'common.noActivities': 'No activities set',
        'common.profilePhoto': 'Profile photo',
        'common.profilePhotoNumber': 'Profile photo {count}',
        'common.removePhoto': 'Remove photo',
        'common.previousPhoto': 'Previous photo',
        'common.nextPhoto': 'Next photo',
        'common.main': 'Main',
        'home.tagline': 'Find your perfect sports partner.',
        'home.taglineSecond': 'Swipe. Match. Play.',
        'meta.description': 'Match people for sports activities near you',
        'home.google': 'Continue with Google',
        'home.email': 'Continue with email',
        'home.signingIn': 'Signing in...',
        'auth.welcome': 'Welcome back',
        'auth.join': 'Join FIT-M8',
        'auth.loginSubtitle': 'Sign in to find your next match',
        'auth.registerSubtitle': 'Create your sports profile',
        'auth.or': 'or',
        'auth.email': 'Email address',
        'auth.password': 'Password',
        'auth.confirmPassword': 'Confirm password',
        'auth.loading': 'Loading...',
        'auth.signIn': 'Sign in',
        'auth.createAccount': 'Create account',
        'auth.noAccount': "Don't have an account?",
        'auth.haveAccount': 'Already have an account?',
        'auth.signUp': 'Sign up',
        'auth.passwordMismatch': 'Passwords do not match',
        'auth.forgotPassword': 'Forgot password?',
        'auth.enterEmailFirst': 'Enter your email address above first',
        'auth.resetEmailSent': 'Password reset email sent. Check your inbox.',
        'auth.verifyEmailTitle': 'Verify your email',
        'auth.verifyEmailHint': "We've sent a verification link to {email}. Confirm it to start appearing in Discover.",
        'auth.resendVerification': 'Resend verification email',
        'auth.verificationEmailSent': 'Verification email sent. Check your inbox.',
        'auth.iHaveVerified': "I've verified my email",
        'auth.stillNotVerified': "Still not verified. Check your inbox (and spam folder).",
        'auth.errorEmailInUse': 'An account with this email already exists. Try signing in instead.',
        'auth.errorInvalidEmail': 'Enter a valid email address.',
        'auth.errorWeakPassword': 'Choose a stronger password (at least 6 characters).',
        'auth.errorInvalidCredential': 'Incorrect email or password.',
        'auth.errorTooManyRequests': 'Too many attempts. Please wait a moment and try again.',
        'auth.emailVerifiedSuccess': 'Your email has been verified!',
        'errors.generic': 'Something went wrong',
        'onboarding.chooseLanguage': 'Choose your language',
        'onboarding.languageHint': 'You can change this later in your settings',
        'onboarding.permissionsTitle': 'Stay in the loop',
        'onboarding.permissionsHint': "We'll ask for a couple of permissions to get you set up",
        'onboarding.notificationsTitle': 'Push notifications',
        'onboarding.notificationsHint': 'Get notified about new matches and messages',
        'onboarding.enableNotifications': 'Enable notifications',
        'onboarding.notificationsEnabled': 'Notifications enabled',
        'onboarding.notificationsBlocked': 'Blocked — enable notifications in your browser settings',
        'onboarding.locationTitle': 'Location',
        'onboarding.locationHint': 'Used to find sports partners near you',
        'onboarding.aboutYou': 'About you',
        'onboarding.aboutYouHint': 'Tell us who you are',
        'onboarding.name': 'Your name',
        'onboarding.nameError': 'Please enter your first name only',
        'onboarding.bioOptional': 'Short bio (optional)',
        'onboarding.age': 'Age',
        'onboarding.birthdate': 'Date of birth',
        'onboarding.underageError': 'You must be at least 18 years old to use FIT-M8',
        'onboarding.yourSports': 'Your sports',
        'onboarding.sportsHint': 'Pick at least one activity you enjoy',
        'onboarding.selectAtLeastOneSport': 'Pick at least one sport to continue',
        'onboarding.yourSettings': 'Your settings',
        'onboarding.settingsHint': 'For each sport, pick format and level',
        'onboarding.howItWorks': 'How it works',
        'onboarding.howItWorksHint': 'Your filters decide who you meet',
        'onboarding.profilePhotos': 'Profile photo',
        'onboarding.photosHint': 'Add a photo so others can find you.',
        'onboarding.photosRequired': 'Add a photo to continue',
        'onboarding.makeItYours': 'Finishing touches',
        'onboarding.appearanceHint': 'Set your location, notifications and app style',
        'intro.skip': 'Skip',
        'intro.next': 'Next',
        'intro.dating.title': 'Find a date',
        'intro.dating.body': 'Set your gender and orientation filters to meet people you click with while doing the sports you love.',
        'intro.friends.title': 'Make new friends',
        'intro.friends.body': 'Not looking to date? Turn the filters off and simply find training partners to share a session with.',
        'intro.experts.title': 'Learn from experts',
        'intro.experts.body': 'Filter by Expert level to find experienced players and trainers who can help you step up your game.',
        'discover.filters': 'Filters',
        'discover.datingPreset': 'Dating',
        'discover.friendsPreset': 'Friends',
        'discover.trainerPreset': 'Trainer',
        'discover.titleDating': 'Dating',
        'discover.titleFriends': 'Friends',
        'discover.titleTrainer': 'Trainers',
        'discover.presetHintToggle': 'How it works',
        'discover.presetHintSubtitle': 'Your sports are the heart of every match.',
        'discover.presetHintPickOne': 'Pick one to continue',
        'discover.presetHintSwipeTitle': "It's a swipe app",
        'discover.presetHintSwipeBody': 'Swipe right (or tap ⚡) to like someone, swipe left (or tap ✕) to pass. Like each other and it’s a match!',
        'discover.presetHintIntroTitle': 'Your sports, your matches',
        'discover.presetHintIntroBody': 'We match you with people who share the sports and activities on your profile — the more you add, the more people you can connect with.',
        'discover.presetHintOrderTitle': 'Order sets your priority',
        'discover.presetHintOrderBody': 'The order of your sports list matters: the ones at the top count more when we look for matches, so put your favorites first.',
        'discover.presetHintDatingBody': 'Sets gender and orientation filters so you meet people you could hit it off with.',
        'discover.presetHintFriendsBody': 'Turns off dating filters and simply finds training partners to share a session with.',
        'discover.presetHintTrainerBody': 'Filters by Expert level to find experienced players and trainers who can help you improve.',
        'discover.ageRange': 'Age range',
        'discover.distance': 'Distance',
        'discover.locationHint': 'Enable location detection in your profile to filter by distance.',
        'discover.allSports': 'All sports',
        'discover.refresh': 'Refresh',
        'discover.tryFilters': 'Try changing your filters or check back later',
        'discover.withinKm': 'Within {count} km',
        'discover.noMorePlayers': 'No more players',
        'discover.singleFilter': 'Single',
        'discover.trainerFilter': 'Trainer',
        'discover.matchTitle': "It's a Match!",
        'discover.matchHint': 'You can now chat and plan your session!',
        'discover.matchNone': 'No matches found',
        'discover.matchOne': 'Match 1 person',
        'discover.matchMany': 'Match {count} people',
        'matches.subtitle': 'People you matched with',
        'matches.loadError': "Couldn't load matches",
        'matches.emptyTitle': 'No matches yet',
        'matches.emptyHint': 'Keep swiping to find your sports partner!',
        'matches.goDiscover': 'Go to Discover',
        'matches.viewMatches': 'View matches',
        'matches.fallback': 'Match',
        'matches.directMessage': 'Direct message',
        'chat.fallbackTitle': 'Match Chat',
        'chat.emptyTitle': 'Say hi to your match!',
        'chat.emptyHint': 'Plan your activity session together',
        'chat.placeholder': 'Type a message...',
        'chat.menu': 'Options',
        'chat.unmatch': 'Remove match',
        'chat.unmatchTitle': 'Remove match?',
        'chat.unmatchHint': "This deletes the conversation and removes you both from each other's matches. This can't be undone.",
        'chat.unmatching': 'Removing...',
        'chat.report': 'Report user',
        'chat.reportTitle': 'Report user',
        'chat.reportHint': "Tell us what's going on. Our team will review it.",
        'chat.reportReasonHarassment': 'Harassment or abuse',
        'chat.reportReasonInappropriate': 'Inappropriate messages or photos',
        'chat.reportReasonFakeProfile': 'Fake profile',
        'chat.reportReasonSpam': 'Spam or scam',
        'chat.reportReasonOther': 'Other',
        'chat.reportDetailsPlaceholder': 'Add details (optional)',
        'chat.reportSubmit': 'Submit report',
        'chat.reporting': 'Submitting...',
        'chat.reportSuccess': "Report submitted. Thanks for letting us know.",
        'profile.edit': 'Edit',
        'profile.editTitle': 'Edit profile',
        'profile.share': 'Share',
        'profile.viewProfile': 'View profile',
        'premium.messageUpsellTitle': 'Direct messages are a Premium feature',
        'premium.messageUpsellHint': "Subscribe to FIT-M8 Premium to message anyone directly — no need to match first.",
        'profile.bio': 'Your bio...',
        'profile.signOut': 'Sign out',
        'profile.notFound': 'User not found',
        'profile.inCommon': 'In common',
        'profile.distanceAway': '{count} km away',
        'profile.addSport': 'Add a sport',
        'profile.allSports': "You've added every sport already!",
        'profile.addSportButton': 'Add sport',
        'profile.resetSwipes': 'Reset swipes',
        'profile.resettingSwipes': 'Resetting...',
        'profile.resetSwipesTitle': 'Reset swipes?',
        'profile.resetSwipesHint': "This also removes your current matches. This can't be undone.",
        'profile.discovery': 'Discovery',
        'profile.dangerZone': 'Danger zone',
        'profile.deleteAccount': 'Delete account',
        'profile.deletingAccount': 'Deleting...',
        'profile.deleteAccountTitle': 'Delete account?',
        'profile.deleteAccountHint': "This permanently deletes your profile, photos, swipes, matches and messages. This can't be undone.",
        'errors.requiresRecentLogin': 'Please sign out and sign back in, then try again.',
        'common.delete': 'Delete',
        'profile.statusTitle': 'Status',
        'profile.single': 'Single',
        'profile.trainer': 'Trainer',
        'appearance.title': 'Appearance',
        'appearance.light': 'Light',
        'appearance.dark': 'Dark',
        'appearance.appTheme': 'App Theme',
        'appearance.classic': 'Classic',
        'appearance.ocean': 'Ocean',
        'appearance.sunset': 'Sunset',
        'appearance.forest': 'Forest',
        'appearance.berry': 'Berry',
        'appearance.slate': 'Slate',
        'location.enterCity': 'Enter your city',
        'location.editCity': 'Edit city',
        'location.detecting': 'Detecting...',
        'location.useMyLocation': 'Use my location',
        'location.denied': 'Location access denied',
        'location.unsupported': "Geolocation isn't supported on this device",
        'location.detectFailed': "Couldn't detect your location",
        'location.resolveFailed': "Couldn't resolve your city",
        'location.outsideBarcelona': 'FIT-M8 is currently only available in Barcelona',
        'photo.chooseImage': 'Please choose an image file',
        'photo.uploadFailed': 'Upload failed',
        'activity.jogging': 'Jogging',
        'activity.padel': 'Padel',
        'activity.tennis': 'Tennis',
        'activity.beachVolley': 'Beach Volley',
        'activity.footvolley': 'Foot Volley',
        'activity.basketball': 'Basketball',
        'activity.soccer': 'Football',
        'activity.cycling': 'Cycling',
        'activity.swimming': 'Swimming',
        'activity.hiking': 'Hiking',
        'activity.badminton': 'Badminton',
        'activity.pingPong': 'Ping Pong',
        'activity.pickleball': 'Pickleball',
        'activity.squash': 'Squash',
        'activity.frescobol': 'Frescobol',
        'activity.gym': 'Gym Training',
        'activity.calisthenics': 'Calisthenics',
        'activity.yoga': 'Yoga',
        'activity.rockClimbing': 'Rock Climbing',
        'activity.golf': 'Golf',
        'activity.martialArts': 'Martial Arts',
        'activity.paddleboard': 'Paddleboard',
        'activity.surf': 'Surfing',
        'activity.rollerblade': 'Rollerblading',
        'activity.skateboard': 'Skateboarding',
        'format.all': 'All',
        'format.1v1': '1v1',
        'format.2v2': '2v2',
        'format.group': '4+',
        'skill.basic': 'Basic',
        'skill.medium': 'Medium',
        'skill.expert': 'Expert',
        'gender.male': 'Male',
        'gender.female': 'Female',
        'orientation.hetero': 'Hetero',
        'orientation.gay': 'Gay',
        'profile.addSports': 'Add {count} sports',
        'common.language': 'Language',
        'sports.maxHint': 'You can pick up to {max} sports',
        'sports.maxReached': "You've reached the {max}-sport limit",
        'sports.reorderHint': 'Drag to reorder — sports higher on the list rank you higher in Discover for that sport',
        'common.dragToReorder': 'Drag to reorder',
        'premium.title': 'FIT-M8 Premium',
        'premium.subtitle': 'Unlock more from your FIT-M8 experience',
        'premium.priceLine': '$9.99 / month',
        'premium.featureMoreSportsTitle': 'Add more sports',
        'premium.featureMoreSportsHint': 'Track up to {max} sports instead of {free}',
        'premium.featureDirectMessageTitle': 'Message anyone directly',
        'premium.featureDirectMessageHint': "Skip the match — reach out to any profile you're interested in",
        'premium.featureTrainerEventsTitle': 'Host events as a trainer',
        'premium.featureTrainerEventsHint': 'Create and promote sessions for people to join',
        'premium.comingSoon': 'Coming soon',
        'premium.subscribeButton': 'Subscribe now',
        'premium.inviteOnlyHint': 'Membership is invite-only right now — check back soon.',
        'premium.activeTitle': "You're Premium",
        'premium.activeHint': 'Thanks for supporting FIT-M8! Every premium feature is unlocked.',
        'premium.cancelButton': 'Cancel subscription',
        'profile.goPremium': 'Go Premium',
        'profile.premiumMember': 'Premium member',
        'profile.premiumFeature': 'Premium',
        'profile.socialLinks': 'Social links',
        'profile.socialLinksHint': 'Add links to your Instagram, WhatsApp, or other profiles',
        'profile.socialLinkPlaceholder': 'instagram.com/you',
        'profile.invalidSocialLink': 'Enter a valid link',
        'common.add': 'Add',
        'common.remove': 'Remove'
    },
    es: {
        'meta.description': 'Conecta con personas para hacer deporte cerca de ti', 'language.en': 'Inglés', 'language.es': 'Español', 'language.pt': 'Portugués',
        'nav.discover': 'Descubrir', 'nav.matches': 'Coincidencias', 'nav.profile': 'Perfil', 'common.all': 'Todos', 'common.any': 'Cualquiera', 'common.search': 'Buscar', 'common.noResults': 'Sin resultados', 'common.showMore': 'Más +', 'common.save': 'Guardar', 'common.saving': 'Guardando...', 'common.refresh': 'Actualizar', 'common.close': 'Cerrar', 'common.back': 'Volver', 'common.loading': 'Cargando...', 'common.chat': 'Chat', 'common.match': 'Match', 'common.format': 'Formato', 'common.level': 'Nivel', 'common.gender': 'Género', 'common.orientation': 'Orientación', 'common.sports': 'Deportes', 'common.mySports': 'Mis deportes', 'common.noActivities': 'No hay actividades configuradas', 'common.profilePhoto': 'Foto de perfil', 'common.profilePhotoNumber': 'Foto de perfil {count}', 'common.removePhoto': 'Eliminar foto', 'common.previousPhoto': 'Foto anterior', 'common.nextPhoto': 'Foto siguiente', 'common.main': 'Principal', 'home.tagline': 'Encuentra tu pareja deportiva ideal.', 'home.taglineSecond': 'Desliza. Conecta. Juega.', 'home.google': 'Continuar con Google', 'home.email': 'Continuar con email', 'home.signingIn': 'Iniciando sesión...', 'auth.welcome': 'Te damos la bienvenida', 'auth.join': 'Únete a FIT-M8', 'auth.loginSubtitle': 'Inicia sesión para encontrar tu próxima conexión', 'auth.registerSubtitle': 'Crea tu perfil deportivo', 'auth.or': 'o', 'auth.email': 'Correo electrónico', 'auth.password': 'Contraseña', 'auth.confirmPassword': 'Confirmar contraseña', 'auth.loading': 'Cargando...', 'auth.signIn': 'Iniciar sesión', 'auth.createAccount': 'Crear cuenta', 'auth.noAccount': '¿No tienes una cuenta?', 'auth.haveAccount': '¿Ya tienes una cuenta?', 'auth.signUp': 'Registrarse', 'auth.passwordMismatch': 'Las contraseñas no coinciden', 'errors.generic': 'Algo salió mal', 'onboarding.chooseLanguage': 'Elige tu idioma', 'onboarding.languageHint': 'Puedes cambiarlo más tarde en tus ajustes', 'onboarding.permissionsTitle': 'Mantente al día', 'onboarding.permissionsHint': 'Te pediremos un par de permisos para configurarlo todo', 'onboarding.notificationsTitle': 'Notificaciones push', 'onboarding.notificationsHint': 'Recibe avisos de nuevos matches y mensajes', 'onboarding.enableNotifications': 'Activar notificaciones', 'onboarding.notificationsEnabled': 'Notificaciones activadas', 'onboarding.notificationsBlocked': 'Bloqueadas — actívalas en los ajustes de tu navegador', 'onboarding.locationTitle': 'Ubicación', 'onboarding.locationHint': 'Se usa para encontrar compañeros de deporte cerca de ti', 'onboarding.aboutYou': 'Sobre ti', 'onboarding.aboutYouHint': 'Cuéntanos quién eres', 'onboarding.name': 'Tu nombre', 'onboarding.nameError': 'Introduce solo tu nombre', 'onboarding.bioOptional': 'Biografía breve (opcional)', 'onboarding.age': 'Edad', 'onboarding.birthdate': 'Fecha de nacimiento', 'onboarding.underageError': 'Debes tener al menos 18 años para usar FIT-M8', 'onboarding.yourSports': 'Tus deportes', 'onboarding.sportsHint': 'Elige las actividades que disfrutas', 'onboarding.selectAtLeastOneSport': 'Elige al menos un deporte para continuar', 'onboarding.yourSettings': 'Tus ajustes', 'onboarding.settingsHint': 'Elige formato y nivel para cada deporte', 'onboarding.profilePhotos': 'Fotos de perfil', 'onboarding.photosHint': 'Añade hasta 3 fotos para que otros puedan encontrarte. La primera será tu foto principal.', 'onboarding.photosRequired': 'Añade al menos una foto para continuar', 'onboarding.makeItYours': 'Últimos detalles', 'onboarding.appearanceHint': 'Configura tu ubicación, notificaciones y el estilo de la app', 'discover.filters': 'Filtros', 'discover.datingPreset': 'Citas', 'discover.friendsPreset': 'Amistad', 'discover.trainerPreset': 'Entrenador', 'discover.titleDating': 'Citas', 'discover.titleFriends': 'Amistad', 'discover.titleTrainer': 'Entrenadores', 'discover.ageRange': 'Rango de edad', 'discover.distance': 'Distancia', 'discover.withinKm': 'A menos de {count} km', 'discover.noMorePlayers': 'No hay más jugadores', 'discover.matchTitle': '¡Es una coincidencia!', 'discover.matchHint': '¡Ahora pueden chatear y planear su sesión!', 'matches.subtitle': 'Personas con las que coincidiste', 'matches.loadError': 'No se pudieron cargar las coincidencias', 'matches.emptyTitle': 'Aún no hay coincidencias', 'matches.emptyHint': '¡Sigue deslizando para encontrar tu pareja deportiva!', 'matches.goDiscover': 'Ir a Descubrir', 'matches.fallback': 'Coincidencia', 'chat.fallbackTitle': 'Chat de coincidencia', 'chat.emptyTitle': '¡Saluda a tu coincidencia!', 'chat.emptyHint': 'Planifiquen juntos su sesión deportiva', 'chat.placeholder': 'Escribe un mensaje...', 'profile.edit': 'Editar', 'profile.editTitle': 'Editar perfil', 'profile.bio': 'Tu biografía...', 'profile.signOut': 'Cerrar sesión', 'profile.notFound': 'Usuario no encontrado', 'profile.inCommon': 'En común', 'profile.addSport': 'Añadir un deporte', 'profile.allSports': '¡Ya has añadido todos los deportes!', 'profile.addSportButton': 'Añadir deporte', 'profile.resetSwipes': 'Restablecer deslizes', 'profile.resettingSwipes': 'Restableciendo...', 'appearance.title': 'Apariencia', 'appearance.light': 'Claro', 'appearance.dark': 'Oscuro', 'appearance.appTheme': 'Tema de la aplicación', 'location.enterCity': 'Escribe tu ciudad', 'location.editCity': 'Editar ciudad', 'location.detecting': 'Detectando...', 'location.useMyLocation': 'Usar mi ubicación', 'location.denied': 'Acceso a la ubicación denegado', 'location.unsupported': 'La geolocalización no es compatible con este dispositivo', 'location.detectFailed': 'No se pudo detectar tu ubicación', 'location.resolveFailed': 'No se pudo encontrar tu ciudad', 'photo.chooseImage': 'Elige un archivo de imagen', 'photo.uploadFailed': 'No se pudo subir la imagen', 'activity.jogging': 'Correr', 'activity.padel': 'Pádel', 'activity.tennis': 'Tenis', 'activity.beachVolley': 'Vóley playa', 'activity.footvolley': 'Futevóley', 'activity.basketball': 'Baloncesto', 'activity.cycling': 'Ciclismo', 'activity.swimming': 'Natación', 'activity.hiking': 'Senderismo', 'activity.badminton': 'Bádminton', 'activity.ping-pong': 'Ping-pong', 'activity.pickleball': 'Pickleball', 'activity.squash': 'Squash', 'activity.frescobol': 'Frescobol', 'activity.gym': 'Entrenamiento en gimnasio', 'activity.calisthenics': 'Calistenia', 'activity.yoga': 'Yoga', 'activity.rock-climbing': 'Escalada', 'activity.golf': 'Golf', 'activity.martial-arts': 'Artes marciales', 'activity.paddleboard': 'Paddle surf', 'activity.surf': 'Surf', 'activity.rollerblade': 'Patinaje en línea', 'activity.skateboard': 'Monopatín', 'activity.soccer': 'Fútbol', 'format.all': 'Todos', 'format.1v1': '1 contra 1', 'format.2v2': '2 contra 2', 'format.group': '4+', 'skill.basic': 'Básico', 'skill.medium': 'Medio', 'skill.expert': 'Experto', 'gender.male': 'Hombre', 'gender.female': 'Mujer', 'orientation.hetero': 'Hetero', 'orientation.gay': 'Gay'
    },
    pt: {
        'meta.description': 'Combina com pessoas para praticar desporto perto de ti', 'language.en': 'Inglês', 'language.es': 'Espanhol', 'language.pt': 'Português',
        'nav.discover': 'Descobrir', 'nav.matches': 'Combinações', 'nav.profile': 'Perfil', 'common.all': 'Todos', 'common.any': 'Qualquer', 'common.search': 'Pesquisar', 'common.noResults': 'Sem resultados', 'common.showMore': 'Mais +', 'common.save': 'Guardar', 'common.saving': 'A guardar...', 'common.refresh': 'Atualizar', 'common.close': 'Fechar', 'common.back': 'Voltar', 'common.loading': 'A carregar...', 'common.chat': 'Chat', 'common.match': 'Match', 'common.format': 'Formato', 'common.level': 'Nível', 'common.gender': 'Género', 'common.orientation': 'Orientação', 'common.sports': 'Desportos', 'common.mySports': 'Os meus desportos', 'common.noActivities': 'Nenhuma atividade definida', 'common.profilePhoto': 'Foto de perfil', 'common.profilePhotoNumber': 'Foto de perfil {count}', 'common.removePhoto': 'Remover foto', 'common.previousPhoto': 'Foto anterior', 'common.nextPhoto': 'Foto seguinte', 'common.main': 'Principal', 'home.tagline': 'Encontra o teu parceiro desportivo ideal.', 'home.taglineSecond': 'Desliza. Combina. Joga.', 'home.google': 'Continuar com o Google', 'home.email': 'Continuar com email', 'home.signingIn': 'A iniciar sessão...', 'auth.welcome': 'Bem-vindo de volta', 'auth.join': 'Junta-te ao FIT-M8', 'auth.loginSubtitle': 'Inicia sessão para encontrar a tua próxima combinação', 'auth.registerSubtitle': 'Cria o teu perfil desportivo', 'auth.or': 'ou', 'auth.email': 'Endereço de email', 'auth.password': 'Palavra-passe', 'auth.confirmPassword': 'Confirmar palavra-passe', 'auth.loading': 'A carregar...', 'auth.signIn': 'Iniciar sessão', 'auth.createAccount': 'Criar conta', 'auth.noAccount': 'Ainda não tens conta?', 'auth.haveAccount': 'Já tens uma conta?', 'auth.signUp': 'Registar', 'auth.passwordMismatch': 'As palavras-passe não coincidem', 'errors.generic': 'Ocorreu um erro', 'onboarding.chooseLanguage': 'Escolhe o teu idioma', 'onboarding.languageHint': 'Podes alterar isto mais tarde nas definições', 'onboarding.permissionsTitle': 'Mantém-te a par', 'onboarding.permissionsHint': 'Vamos pedir-te algumas permissões para tudo ficar pronto', 'onboarding.notificationsTitle': 'Notificações push', 'onboarding.notificationsHint': 'Recebe avisos de novos matches e mensagens', 'onboarding.enableNotifications': 'Ativar notificações', 'onboarding.notificationsEnabled': 'Notificações ativadas', 'onboarding.notificationsBlocked': 'Bloqueadas — ativa-as nas definições do teu navegador', 'onboarding.locationTitle': 'Localização', 'onboarding.locationHint': 'Usada para encontrar parceiros de desporto perto de ti', 'onboarding.aboutYou': 'Sobre ti', 'onboarding.aboutYouHint': 'Conta-nos quem és', 'onboarding.name': 'O teu nome', 'onboarding.nameError': 'Indica apenas o teu primeiro nome', 'onboarding.bioOptional': 'Breve biografia (opcional)', 'onboarding.age': 'Idade', 'onboarding.birthdate': 'Data de nascimento', 'onboarding.underageError': 'Tens de ter pelo menos 18 anos para usar o FIT-M8', 'onboarding.yourSports': 'Os teus desportos', 'onboarding.sportsHint': 'Escolhe as atividades de que gostas', 'onboarding.selectAtLeastOneSport': 'Escolhe pelo menos um desporto para continuar', 'onboarding.yourSettings': 'As tuas definições', 'onboarding.settingsHint': 'Escolhe o formato e o nível de cada desporto', 'onboarding.profilePhotos': 'Fotos de perfil', 'onboarding.photosHint': 'Adiciona até 3 fotos para que te possam encontrar. A primeira será a principal.', 'onboarding.photosRequired': 'Adiciona pelo menos uma foto para continuar', 'onboarding.makeItYours': 'Últimos retoques', 'onboarding.appearanceHint': 'Define a tua localização, notificações e o estilo da app', 'discover.filters': 'Filtros', 'discover.datingPreset': 'Encontros', 'discover.friendsPreset': 'Amizade', 'discover.trainerPreset': 'Treinador', 'discover.titleDating': 'Encontros', 'discover.titleFriends': 'Amizade', 'discover.titleTrainer': 'Treinadores', 'discover.ageRange': 'Intervalo de idade', 'discover.distance': 'Distância', 'discover.withinKm': 'Num raio de {count} km', 'discover.noMorePlayers': 'Não há mais jogadores', 'discover.matchTitle': 'É uma combinação!', 'discover.matchHint': 'Agora podem conversar e planear a sessão!', 'matches.subtitle': 'Pessoas com quem combinaste', 'matches.loadError': 'Não foi possível carregar as combinações', 'matches.emptyTitle': 'Ainda não há combinações', 'matches.emptyHint': 'Continua a deslizar para encontrares o teu parceiro desportivo!', 'matches.goDiscover': 'Ir para Descobrir', 'matches.fallback': 'Combinação', 'chat.fallbackTitle': 'Chat da combinação', 'chat.emptyTitle': 'Diz olá à tua combinação!', 'chat.emptyHint': 'Planeiem juntos a vossa sessão desportiva', 'chat.placeholder': 'Escreve uma mensagem...', 'profile.edit': 'Editar', 'profile.editTitle': 'Editar perfil', 'profile.bio': 'A tua biografia...', 'profile.signOut': 'Terminar sessão', 'profile.notFound': 'Utilizador não encontrado', 'profile.inCommon': 'Em comum', 'profile.addSport': 'Adicionar um desporto', 'profile.allSports': 'Já adicionaste todos os desportos!', 'profile.addSportButton': 'Adicionar desporto', 'profile.resetSwipes': 'Repor deslizes', 'profile.resettingSwipes': 'A repor...', 'appearance.title': 'Aparência', 'appearance.light': 'Claro', 'appearance.dark': 'Escuro', 'appearance.appTheme': 'Tema da aplicação', 'location.enterCity': 'Introduz a tua cidade', 'location.editCity': 'Editar cidade', 'location.detecting': 'A detetar...', 'location.useMyLocation': 'Usar a minha localização', 'location.denied': 'Acesso à localização negado', 'location.unsupported': 'A geolocalização não é suportada neste dispositivo', 'location.detectFailed': 'Não foi possível detetar a tua localização', 'location.resolveFailed': 'Não foi possível encontrar a tua cidade', 'photo.chooseImage': 'Escolhe um ficheiro de imagem', 'photo.uploadFailed': 'Não foi possível carregar a imagem', 'activity.jogging': 'Corrida', 'activity.padel': 'Padel', 'activity.tennis': 'Ténis', 'activity.beachVolley': 'Voleibol de praia', 'activity.footvolley': 'Futevólei', 'activity.basketball': 'Basquetebol', 'activity.cycling': 'Ciclismo', 'activity.swimming': 'Natação', 'activity.hiking': 'Caminhada', 'activity.badminton': 'Badminton', 'activity.ping-pong': 'Ténis de mesa', 'activity.pickleball': 'Pickleball', 'activity.squash': 'Squash', 'activity.frescobol': 'Frescobol', 'activity.gym': 'Treino de ginásio', 'activity.calisthenics': 'Calistenia', 'activity.yoga': 'Yoga', 'activity.rock-climbing': 'Escalada', 'activity.golf': 'Golfe', 'activity.martial-arts': 'Artes marciais', 'activity.paddleboard': 'Paddleboard', 'activity.surf': 'Surf', 'activity.rollerblade': 'Patins em linha', 'activity.skateboard': 'Skate', 'activity.soccer': 'Futebol', 'format.all': 'Todos', 'format.1v1': '1 contra 1', 'format.2v2': '2 contra 2', 'format.group': '4+', 'skill.basic': 'Básico', 'skill.medium': 'Médio', 'skill.expert': 'Perito', 'gender.male': 'Masculino', 'gender.female': 'Feminino', 'orientation.hetero': 'Hetero', 'orientation.gay': 'Gay'
    }
} as const;

export type TranslationKey = keyof typeof MESSAGES.en;
export type TranslationParams = Record<string, string | number>;

const EXTRA_MESSAGES: Record<LanguageCode, Partial<Record<TranslationKey, string>>> = {
    en: {},
    es: {
        'common.yes': 'Sí',
        'common.no': 'No',
        'discover.presetHintToggle': '¿Citas, amistad o entrenador?',
        'discover.presetHintSubtitle': 'Descubre qué ajusta cada filtro rápido.',
        'discover.presetHintPickOne': 'Elige una opción para continuar',
        'discover.presetHintDatingBody': 'Configura los filtros de género y orientación para conocer a personas con las que conectes.',
        'discover.presetHintFriendsBody': 'Desactiva los filtros de citas y busca compañeros de entrenamiento para compartir una sesión.',
        'discover.presetHintTrainerBody': 'Filtra por nivel Experto para encontrar jugadores y entrenadores con experiencia que te ayuden a mejorar.',
        'location.outsideBarcelona': 'FIT-M8 solo está disponible en Barcelona por ahora',
        'auth.forgotPassword': '¿Olvidaste tu contraseña?',
        'auth.enterEmailFirst': 'Introduce primero tu correo electrónico',
        'auth.resetEmailSent': 'Correo de restablecimiento enviado. Revisa tu bandeja de entrada.',
        'auth.verifyEmailTitle': 'Verifica tu correo electrónico',
        'auth.verifyEmailHint': 'Hemos enviado un enlace de verificación a {email}. Confírmalo para empezar a aparecer en Descubrir.',
        'auth.resendVerification': 'Reenviar correo de verificación',
        'auth.verificationEmailSent': 'Correo de verificación enviado. Revisa tu bandeja de entrada.',
        'auth.iHaveVerified': 'Ya he verificado mi correo',
        'auth.stillNotVerified': 'Todavía no está verificado. Revisa tu bandeja de entrada (y spam).',
        'auth.errorEmailInUse': 'Ya existe una cuenta con este correo. Intenta iniciar sesión.',
        'auth.errorInvalidEmail': 'Introduce un correo electrónico válido.',
        'auth.errorWeakPassword': 'Elige una contraseña más segura (al menos 6 caracteres).',
        'auth.errorInvalidCredential': 'Correo o contraseña incorrectos.',
        'auth.errorTooManyRequests': 'Demasiados intentos. Espera un momento e intenta de nuevo.',
        'auth.emailVerifiedSuccess': '¡Tu correo electrónico ha sido verificado!',
        'onboarding.howItWorks': 'Cómo funciona',
        'onboarding.howItWorksHint': 'Tus filtros deciden a quién conoces',
        'discover.matchNone': 'Ningún resultado',
        'discover.matchOne': 'Conectar con 1 persona',
        'discover.matchMany': 'Conectar con {count} personas',
        'profile.distanceAway': 'A {count} km',
        'intro.skip': 'Omitir',
        'intro.next': 'Siguiente',
        'intro.dating.title': 'Encuentra una cita',
        'intro.dating.body': 'Configura tus filtros de género y orientación para conocer a personas con las que conectes mientras practicas los deportes que te gustan.',
        'intro.friends.title': 'Haz nuevos amigos',
        'intro.friends.body': '¿No buscas una cita? Desactiva los filtros y encuentra compañeros de entrenamiento para compartir una sesión.',
        'intro.experts.title': 'Aprende de expertos',
        'intro.experts.body': 'Filtra por nivel Experto para encontrar jugadores y entrenadores con experiencia que te ayuden a mejorar tu juego.',
        'common.language': 'Idioma',
        'common.name': 'Nombre',
        'common.email': 'Correo electrónico',
        'common.biography': 'Biografía',
        'common.location': 'Ubicación',
        'discover.singleFilter': 'Soltero/a',
        'discover.trainerFilter': 'Entrenador/a',
        'profile.statusTitle': 'Estado',
        'profile.single': 'Soltero/a',
        'profile.trainer': 'Entrenador/a',
        'common.message': 'Mensaje',
        'common.gotIt': 'Entendido',
        'common.maybeLater': 'Quizás más tarde',
        'common.undo': 'Deshacer',
        'profile.share': 'Compartir', 'profile.viewProfile': 'Ver perfil',
        'premium.messageUpsellTitle': 'Los mensajes directos son una función Premium',
        'premium.messageUpsellHint': 'Suscríbete a FIT-M8 Premium para escribir directamente a cualquier persona, sin necesidad de hacer match antes.',
        'profile.resetSwipesTitle': '¿Restablecer desplazamientos?',
        'profile.resetSwipesHint': 'Esto también eliminará tus coincidencias actuales. Esta acción no se puede deshacer.',
        'profile.dangerZone': 'Zona de peligro',
        'profile.deleteAccount': 'Eliminar cuenta',
        'profile.deletingAccount': 'Eliminando...',
        'profile.deleteAccountTitle': '¿Eliminar cuenta?',
        'profile.deleteAccountHint': 'Esto elimina permanentemente tu perfil, fotos, deslizamientos, coincidencias y mensajes. Esta acción no se puede deshacer.',
        'errors.requiresRecentLogin': 'Por seguridad, cierra sesión y vuelve a iniciar sesión antes de continuar.',
        'common.delete': 'Eliminar',
        'sports.maxHint': 'Puedes elegir hasta {max} deportes',
        'sports.maxReached': 'Has alcanzado el límite de {max} deportes',
        'sports.reorderHint': 'Arrastra para reordenar: los deportes más arriba te dan más prioridad en Descubrir para ese deporte',
        'common.dragToReorder': 'Arrastra para reordenar',
        'premium.title': 'FIT-M8 Premium',
        'premium.subtitle': 'Desbloquea más funciones de FIT-M8',
        'premium.priceLine': '9,99 $ / mes',
        'premium.featureMoreSportsTitle': 'Añade más deportes',
        'premium.featureMoreSportsHint': 'Sigue hasta {max} deportes en lugar de {free}',
        'premium.featureDirectMessageTitle': 'Escribe directamente a cualquiera',
        'premium.featureDirectMessageHint': 'Sin esperar a hacer match: contacta con cualquier perfil que te interese',
        'premium.featureTrainerEventsTitle': 'Organiza eventos como entrenador',
        'premium.featureTrainerEventsHint': 'Crea y promociona sesiones para que la gente se apunte',
        'premium.comingSoon': 'Próximamente',
        'premium.subscribeButton': 'Suscribirme ahora',
        'premium.inviteOnlyHint': 'La membresía es solo por invitación por ahora — vuelve pronto.',
        'premium.activeTitle': 'Ya eres Premium',
        'premium.activeHint': '¡Gracias por apoyar a FIT-M8! Todas las funciones premium están desbloqueadas.',
        'premium.cancelButton': 'Cancelar suscripción',
        'profile.goPremium': 'Hazte Premium',
        'profile.premiumMember': 'Miembro Premium',
        'profile.premiumFeature': 'Premium',
        'common.keepSwiping': 'Seguir deslizando',
        'matches.viewMatches': 'Ver coincidencias',
        'chat.menu': 'Opciones',
        'chat.unmatch': 'Eliminar coincidencia',
        'chat.unmatchTitle': '¿Eliminar coincidencia?',
        'chat.unmatchHint': 'Esto elimina la conversación y os quita de las coincidencias mutuas. Esta acción no se puede deshacer.',
        'chat.unmatching': 'Eliminando...',
        'chat.report': 'Denunciar usuario',
        'chat.reportTitle': 'Denunciar usuario',
        'chat.reportHint': 'Cuéntanos qué está pasando. Nuestro equipo lo revisará.',
        'chat.reportReasonHarassment': 'Acoso o abuso',
        'chat.reportReasonInappropriate': 'Mensajes o fotos inapropiadas',
        'chat.reportReasonFakeProfile': 'Perfil falso',
        'chat.reportReasonSpam': 'Spam o estafa',
        'chat.reportReasonOther': 'Otro',
        'chat.reportDetailsPlaceholder': 'Añade detalles (opcional)',
        'chat.reportSubmit': 'Enviar denuncia',
        'chat.reporting': 'Enviando...',
        'chat.reportSuccess': 'Denuncia enviada. Gracias por avisarnos.',
        'profile.socialLinks': 'Redes sociales',
        'profile.socialLinksHint': 'Añade enlaces a tu Instagram, WhatsApp u otros perfiles',
        'profile.socialLinkPlaceholder': 'instagram.com/tu_usuario',
        'profile.invalidSocialLink': 'Introduce un enlace válido',
        'common.add': 'Añadir',
        'common.remove': 'Eliminar'
    },
    pt: {
        'common.yes': 'Sim',
        'common.no': 'Não',
        'auth.forgotPassword': 'Esqueceste-te da palavra-passe?',
        'auth.enterEmailFirst': 'Introduz primeiro o teu email',
        'auth.resetEmailSent': 'Email de redefinição enviado. Verifica a tua caixa de entrada.',
        'auth.verifyEmailTitle': 'Verifica o teu email',
        'auth.verifyEmailHint': 'Enviámos um link de verificação para {email}. Confirma-o para começares a aparecer em Descobrir.',
        'auth.resendVerification': 'Reenviar email de verificação',
        'auth.verificationEmailSent': 'Email de verificação enviado. Verifica a tua caixa de entrada.',
        'auth.iHaveVerified': 'Já verifiquei o meu email',
        'auth.stillNotVerified': 'Ainda não verificado. Verifica a tua caixa de entrada (e spam).',
        'auth.errorEmailInUse': 'Já existe uma conta com este email. Tenta iniciar sessão.',
        'auth.errorInvalidEmail': 'Introduz um email válido.',
        'auth.errorWeakPassword': 'Escolhe uma palavra-passe mais forte (pelo menos 6 caracteres).',
        'auth.errorInvalidCredential': 'Email ou palavra-passe incorretos.',
        'auth.errorTooManyRequests': 'Demasiadas tentativas. Espera um momento e tenta novamente.',
        'auth.emailVerifiedSuccess': 'O teu email foi verificado!',
        'onboarding.howItWorks': 'Como funciona',
        'onboarding.howItWorksHint': 'Os teus filtros decidem quem conheces',
        'discover.matchNone': 'Nenhum resultado',
        'discover.matchOne': 'Ligar com 1 pessoa',
        'discover.matchMany': 'Ligar com {count} pessoas',
        'profile.distanceAway': 'A {count} km',
        'intro.skip': 'Saltar',
        'intro.next': 'Seguinte',
        'intro.dating.title': 'Encontra um par',
        'intro.dating.body': 'Define os teus filtros de género e orientação para conheceres pessoas com quem te identifiques enquanto praticas os teus desportos favoritos.',
        'intro.friends.title': 'Faz novos amigos',
        'intro.friends.body': 'Não procuras encontros? Desativa os filtros e encontra parceiros de treino para partilharem uma sessão.',
        'intro.experts.title': 'Aprende com especialistas',
        'intro.experts.body': 'Filtra pelo nível Especialista para encontrares jogadores e treinadores experientes que te podem ajudar a melhorar o teu jogo.',
        'common.language': 'Idioma',
        'common.name': 'Nome',
        'common.email': 'Email',
        'common.biography': 'Biografia',
        'common.location': 'Localização',
        'common.message': 'Mensagem',
        'common.gotIt': 'Entendido',
        'common.maybeLater': 'Talvez depois',
        'common.undo': 'Desfazer',
        'profile.share': 'Partilhar', 'profile.viewProfile': 'Ver perfil',
        'premium.messageUpsellTitle': 'As mensagens diretas são uma funcionalidade Premium',
        'premium.messageUpsellHint': 'Subscreve o FIT-M8 Premium para poderes escrever diretamente a qualquer pessoa, sem precisares de fazer match primeiro.',
        'profile.resetSwipesTitle': 'Repor deslizes?',
        'profile.resetSwipesHint': 'Isto também remove as tuas combinações atuais. Esta ação não pode ser revertida.',
        'profile.dangerZone': 'Zona de perigo',
        'profile.deleteAccount': 'Eliminar conta',
        'profile.deletingAccount': 'A eliminar...',
        'profile.deleteAccountTitle': 'Eliminar conta?',
        'profile.deleteAccountHint': 'Isto elimina permanentemente o teu perfil, fotos, deslizes, combinações e mensagens. Esta ação não pode ser revertida.',
        'errors.requiresRecentLogin': 'Por segurança, termina sessão e inicia sessão novamente antes de continuar.',
        'common.delete': 'Eliminar',
        'sports.maxHint': 'Podes escolher até {max} desportos',
        'sports.maxReached': 'Atingiste o limite de {max} desportos',
        'sports.reorderHint': 'Arrasta para reordenar: os desportos mais acima dão-te mais prioridade em Descobrir para esse desporto',
        'common.dragToReorder': 'Arrasta para reordenar',
        'premium.title': 'FIT-M8 Premium',
        'premium.subtitle': 'Desbloqueia mais funcionalidades do FIT-M8',
        'premium.priceLine': '9,99 $ / mês',
        'premium.featureMoreSportsTitle': 'Adiciona mais desportos',
        'premium.featureMoreSportsHint': 'Acompanha até {max} desportos em vez de {free}',
        'premium.featureDirectMessageTitle': 'Envia mensagens diretas a qualquer pessoa',
        'premium.featureDirectMessageHint': 'Sem esperar por um match: contacta qualquer perfil que te interesse',
        'premium.featureTrainerEventsTitle': 'Organiza eventos como treinador',
        'premium.featureTrainerEventsHint': 'Cria e promove sessões para as pessoas se juntarem',
        'premium.comingSoon': 'Brevemente',
        'premium.subscribeButton': 'Subscrever agora',
        'premium.inviteOnlyHint': 'A adesão é apenas por convite neste momento — volta em breve.',
        'premium.activeTitle': 'Já és Premium',
        'premium.activeHint': 'Obrigado por apoiares o FIT-M8! Todas as funcionalidades premium estão desbloqueadas.',
        'premium.cancelButton': 'Cancelar subscrição',
        'profile.goPremium': 'Torna-te Premium',
        'profile.premiumMember': 'Membro Premium',
        'profile.premiumFeature': 'Premium',
        'common.keepSwiping': 'Continuar a deslizar',
        'matches.viewMatches': 'Ver combinações',
        'chat.menu': 'Opções',
        'chat.unmatch': 'Remover combinação',
        'chat.unmatchTitle': 'Remover combinação?',
        'chat.unmatchHint': 'Isto elimina a conversa e remove-vos das combinações um do outro. Esta ação não pode ser revertida.',
        'chat.unmatching': 'A remover...',
        'chat.report': 'Denunciar utilizador',
        'chat.reportTitle': 'Denunciar utilizador',
        'chat.reportHint': 'Conta-nos o que se passa. A nossa equipa vai analisar.',
        'chat.reportReasonHarassment': 'Assédio ou abuso',
        'chat.reportReasonInappropriate': 'Mensagens ou fotos inapropriadas',
        'chat.reportReasonFakeProfile': 'Perfil falso',
        'chat.reportReasonSpam': 'Spam ou burla',
        'chat.reportReasonOther': 'Outro',
        'chat.reportDetailsPlaceholder': 'Adiciona detalhes (opcional)',
        'chat.reportSubmit': 'Enviar denúncia',
        'chat.reporting': 'A enviar...',
        'chat.reportSuccess': 'Denúncia enviada. Obrigado por nos avisares.',
        'profile.socialLinks': 'Redes sociais',
        'profile.socialLinksHint': 'Adiciona links do teu Instagram, WhatsApp ou outros perfis',
        'profile.socialLinkPlaceholder': 'instagram.com/o-teu-utilizador',
        'profile.invalidSocialLink': 'Introduz um link válido',
        'common.add': 'Adicionar',
        'common.remove': 'Remover',
        'discover.presetHintToggle': 'Encontros, amizade ou treinador?',
        'discover.presetHintSubtitle': 'Descobre o que cada filtro rápido ajusta.',
        'discover.presetHintPickOne': 'Escolhe uma opção para continuar',
        'discover.presetHintDatingBody': 'Define os filtros de género e orientação para conheceres pessoas com quem possas conectar-te.',
        'discover.presetHintFriendsBody': 'Desativa os filtros de encontros e encontra parceiros de treino para partilhar uma sessão.',
        'discover.presetHintTrainerBody': 'Filtra por nível Especialista para encontrares jogadores e treinadores experientes que te ajudem a melhorar.',
        'location.outsideBarcelona': 'O FIT-M8 só está disponível em Barcelona por agora'
    }
};

export interface Translator {
    t: (key: TranslationKey, params?: TranslationParams) => string;
    activity: (id: string) => string;
    format: (value: string) => string;
    skill: (value: string) => string;
    gender: (value: string) => string;
    orientation: (value: string) => string;
}

export function createTranslator(language: LanguageCode): Translator {
    const messages: Partial<Record<TranslationKey, string>> = {
        ...MESSAGES[language],
        ...EXTRA_MESSAGES[language]
    };
    const t = (key: TranslationKey, params: TranslationParams = {}) => {
        const template = messages[key] ?? MESSAGES.en[key] ?? key;
        return template.replace(/\{(\w+)\}/g, (_match: string, name: string) => String(params[name] ?? `{${name}}`));
    };
    const normalizeEnumValue = (value: string) => {
        const normalized = String(value ?? '').trim().toLowerCase();
        if (normalized === 'straight' || normalized === 'Hetero') return 'hetero';
        if (normalized === 'male' || normalized === 'female' || normalized === 'basic' || normalized === 'expert') return normalized;
        return normalized;
    };
    const humanize = (value: string) =>
        String(value ?? '')
            .split(/[-_\s]+/)
            .filter(Boolean)
            .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
            .join(' ');
    const label = (prefix: string, value: string) => {
        const key = `${prefix}.${normalizeEnumValue(value)}` as TranslationKey;
        const translated = t(key);
        return translated === key ? humanize(normalizeEnumValue(value)) : translated;
    };

    return {
        t,
        activity: (id) => label('activity', id),
        format: (value) => value === '1v1' || value === '2v2' ? value : label('format', value),
        skill: (value) => label('skill', value),
        gender: (value) => label('gender', value),
        orientation: (value) => label('orientation', value)
    };
}

const LANGUAGE_KEY = 'fit-m8-language';
const DEFAULT_LANGUAGE: LanguageCode = 'en';

function browserLanguage(): LanguageCode {
    if (typeof navigator === 'undefined') return DEFAULT_LANGUAGE;
    const language = navigator.language.toLowerCase().split('-')[0];
    return LANGUAGES.some((option) => option.code === language)
        ? (language as LanguageCode)
        : DEFAULT_LANGUAGE;
}

function applyLanguage(language: LanguageCode) {
    if (typeof document !== 'undefined') document.documentElement.lang = language;
}

function createLanguageStore() {
    const { subscribe, set } = writable<LanguageCode>(DEFAULT_LANGUAGE);

    return {
        subscribe,
        init: () => {
            if (typeof window === 'undefined') return;
            const savedLanguage = window.localStorage.getItem(LANGUAGE_KEY);
            const language = LANGUAGES.some((option) => option.code === savedLanguage)
                ? (savedLanguage as LanguageCode)
                : browserLanguage();
            applyLanguage(language);
            set(language);
        },
        selectLanguage: (language: LanguageCode) => {
            if (!LANGUAGES.some((option) => option.code === language)) return;
            applyLanguage(language);
            if (typeof window !== 'undefined') window.localStorage.setItem(LANGUAGE_KEY, language);
            set(language);
        },
        // Clears the saved preference and reverts to the browser/default language, e.g. after account deletion.
        reset: () => {
            if (typeof window !== 'undefined') window.localStorage.removeItem(LANGUAGE_KEY);
            const language = browserLanguage();
            applyLanguage(language);
            set(language);
        }
    };
}

export const activeLanguage = createLanguageStore();