import { writable } from 'svelte/store';

export type LanguageCode = 'en' | 'es' | 'it';

export interface LanguageOption {
    code: LanguageCode;
}

export const LANGUAGES: LanguageOption[] = [
    { code: 'en' },
    { code: 'es' },
    { code: 'it' }
];

const MESSAGES = {
    en: {
        'nav.discover': 'Discover',
        'nav.matches': 'Matches',
        'nav.profile': 'Profile',
        'language.en': 'English',
        'language.es': 'Spanish',
        'language.it': 'Italian',
        'common.all': 'All',
        'common.any': 'Any',
        'common.yes': 'Yes',
        'common.no': 'No',
        'common.search': 'Search',
        'common.noResults': 'No results',
        'common.showMore': 'More +',
        'common.save': 'Save',
        'common.saving': 'Saving...',
        'common.refresh': 'Refresh',
        'common.close': 'Close',
        'common.cancel': 'Cancel',
        'common.clear': 'Clear',
        'common.keepSwiping': 'Keep swiping',
        'common.information': 'Information',
        'common.removeSport': 'Remove',
        'common.continue': 'Continue',
        'common.letsGo': "Let's go!",
        'common.like': 'Like',
        'common.pass': 'Pass',
        'common.undo': 'Undo',
        'common.message': 'Message',
        'common.send': 'Send',
        'common.sending': 'Sending...',
        'common.gotIt': 'Got it',
        'common.maybeLater': 'Maybe later',
        'common.back': 'Back',
        'common.loading': 'Loading...',
        'common.chat': 'Chat',
        'common.match': 'Match',
        'common.new': 'New',
        'common.format': 'Format',
        'common.level': 'Level',
        'common.gender': 'Gender',
        'common.orientation': 'Orientation',
        'common.name': 'Name',
        'common.email': 'Email',
        'common.biography': 'Biography',
        'common.location': 'Location',
        'common.sports': 'Activities',
        'common.mySports': 'My Activities',
        'common.noActivities': 'No activities set',
        'common.profilePhoto': 'Profile photo',
        'common.profilePhotoNumber': 'Profile photo {count}',
        'common.removePhoto': 'Remove photo',
        'common.previousPhoto': 'Previous photo',
        'common.nextPhoto': 'Next photo',
        'common.main': 'Main',
        'home.tagline': 'Find your perfect activity partner.',
        'home.taglineSecond': 'Swipe. Match. Play.',
        'home.allActivities': 'All activities',
        'meta.description': 'Match people for activities near you',
        'home.google': 'Continue with Google',
        'home.email': 'Continue with email',
        'home.signingIn': 'Signing in...',
        'home.howItWorksTitle': 'How FIT-M8 works',
        'home.step1Title': 'Create your profile',
        'home.step1Desc': 'Pick the sports and activities you love and set your location.',
        'home.stepFiltersTitle': 'Fine-tune your matches',
        'home.stepFiltersDesc': 'Filter by age, distance, activities and more to find exactly who you’re looking for.',
        'home.step2Title': 'Discover nearby people',
        'home.step2Desc': 'Swipe through people who share your activities near you.',
        'home.step3Title': 'Match and play',
        'home.step3Desc': 'Chat, plan a session, and meet up to play together.',
        'home.activitiesTitle': 'Find a partner for',
        'home.peopleInterested': 'people interested',
        'home.activitiesIntroTitle': 'Match by shared activities',
        'home.activitiesIntroBody': "Add the sports and activities you're into — the more you add, the more people you can match with.",
        'home.activitiesOrderTitle': 'Order shows what matters most',
        'home.activitiesOrderBody': 'The order of your activities list is your priority, so put your favorites first for better matches.',
        'home.followUs': 'Follow us',
        'home.rights': 'All rights reserved.',
        'home.galleryTitle': 'Real activities, real people',
        'auth.welcome': 'Welcome back',
        'auth.join': 'Join FIT-M8',
        'auth.loginSubtitle': 'Sign in to find your next match',
        'auth.registerSubtitle': 'Create your activity profile',
        'auth.or': 'or',
        'auth.email': 'Email address',
        'auth.password': 'Password',
        'auth.confirmPassword': 'Confirm password',
        'auth.loading': 'Loading...',
        'auth.signIn': 'Sign in',
        'auth.createAccount': 'Create account',
        'auth.noAccount': "Don't have an account?",
        'auth.haveAccount': 'Already have an account?',
        'auth.signUp': 'Sign up',
        'auth.passwordMismatch': 'Passwords do not match',
        'auth.forgotPassword': 'Forgot password?',
        'auth.enterEmailFirst': 'Enter your email address above first',
        'auth.resetEmailSent': 'Password reset email sent. Check your inbox.',
        'auth.verifyEmailTitle': 'Verify your email',
        'auth.verifyEmailHint': "We've sent a verification link to {email}. Confirm it to start appearing in Discover.",
        'auth.resendVerification': 'Resend verification email',
        'auth.verificationEmailSent': 'Verification email sent. Check your inbox.',
        'auth.iHaveVerified': "I've verified my email",
        'auth.stillNotVerified': "Still not verified. Check your inbox (and spam folder).",
        'auth.errorEmailInUse': 'An account with this email already exists. Try signing in instead.',
        'auth.errorInvalidEmail': 'Enter a valid email address.',
        'auth.errorWeakPassword': 'Choose a stronger password (at least 6 characters).',
        'auth.errorInvalidCredential': 'Incorrect email or password.',
        'auth.errorTooManyRequests': 'Too many attempts. Please wait a moment and try again.',
        'auth.emailVerifiedSuccess': 'Your email has been verified!',
        'errors.generic': 'Something went wrong',
        'onboarding.chooseLanguage': 'Choose your language',
        'onboarding.languageHint': 'You can change this later in your settings',
        'onboarding.permissionsTitle': 'Stay in the loop',
        'onboarding.permissionsHint': "We'll ask for a couple of permissions to get you set up",
        'onboarding.notificationsTitle': 'Push notifications',
        'onboarding.notificationsHint': 'Get notified about new matches and messages',
        'onboarding.enableNotifications': 'Enable notifications',
        'onboarding.notificationsEnabled': 'Notifications enabled',
        'onboarding.notificationsBlocked': 'Blocked — enable notifications in your browser settings',
        'onboarding.locationTitle': 'Location',
        'onboarding.locationHint': 'Used to find activity partners near you',
        'onboarding.aboutYou': 'About you',
        'onboarding.aboutYouHint': 'Tell us who you are',
        'onboarding.name': 'Your name',
        'onboarding.nameError': 'Please enter your first name only',
        'onboarding.bioOptional': 'Short bio (optional)',
        'onboarding.age': 'Age',
        'onboarding.birthdate': 'Date of birth',
        'onboarding.underageError': 'You must be at least 18 years old to use FIT-M8',
        'onboarding.yourSports': 'Your activities',
        'onboarding.sportsHint': 'Pick at least one activity you enjoy',
        'onboarding.selectAtLeastOneSport': 'Pick at least one activity to continue',
        'onboarding.yourSettings': 'Your settings',
        'onboarding.settingsHint': 'For each activity, pick format and level',
        'onboarding.howItWorks': 'How it works',
        'onboarding.howItWorksHint': 'Your filters decide who you meet',
        'onboarding.profilePhotos': 'Profile photo',
        'onboarding.photosHint': 'Add a photo so others can find you.',
        'onboarding.photosRequired': 'Add a photo to continue',
        'onboarding.makeItYours': 'Finishing touches',
        'onboarding.appearanceHint': 'Set your location, notifications and app style',
        'intro.skip': 'Skip',
        'intro.next': 'Next',
        'intro.dating.title': 'Find a date',
        'intro.dating.body': 'Set your gender and orientation filters to meet people you click with while doing the activities you love.',
        'intro.friends.title': 'Make new friends',
        'intro.friends.body': 'Not looking to date? Turn the filters off and simply find training partners to share a session with.',
        'intro.experts.title': 'Learn from experts',
        'intro.experts.body': 'Filter by Expert level to find experienced players and trainers who can help you step up your game.',
        'discover.filters': 'Filters',
        'discover.datingPreset': 'Dating',
        'discover.friendsPreset': 'Friends',
        'discover.trainerPreset': 'Trainer',
        'discover.defaultPreset': 'Default',
        'discover.titleDating': 'Dating',
        'discover.titleFriends': 'Friends',
        'discover.titleTrainer': 'Trainers',
        'discover.presetHintToggle': 'How it works',
        'discover.presetHintSubtitle': 'Your activities are the heart of every match.',
        'discover.presetHintPickOne': 'Pick one to continue',
        'discover.presetHintSwipeTitle': "It's a swipe app",
        'discover.presetHintSwipeBody': 'Swipe right (or tap ⚡) to like someone, swipe left (or tap ✕) to pass. Like each other and it’s a match!',
        'discover.presetHintIntroTitle': 'Your activities, your matches',
        'discover.presetHintIntroBody': 'We match you with people who share the activities on your profile — the more you add, the more people you can connect with.',
        'discover.presetHintOrderTitle': 'Order sets your priority',
        'discover.presetHintOrderBody': 'The order of your activities list matters: the ones at the top count more when we look for matches, so put your favorites first.',
        'discover.presetHintDefaultBody': 'Clears every filter so you see all activities, ages and distances, with no dating filters applied.',
        'discover.presetHintDatingBody': 'Sets gender and orientation filters so you meet people you could hit it off with.',
        'discover.presetHintFriendsBody': 'Turns off dating filters and simply finds training partners to share a session with.',
        'discover.presetHintTrainerBody': 'Filters by Expert level to find experienced players and trainers who can help you improve.',
        'discover.ageRange': 'Age range',
        'discover.distance': 'Distance',
        'discover.locationHint': 'Enable location detection in your profile to filter by distance.',
        'discover.allSports': 'All activities',
        'discover.refresh': 'Refresh',
        'discover.tryFilters': 'Try changing your filters or check back later',
        'discover.withinKm': 'Within {count} km',
        'discover.noMorePlayers': 'No more players',
        'discover.singleFilter': 'Single',
        'discover.trainerFilter': 'Trainer',
        'discover.matchTitle': "It's a Match!",
        'discover.matchHint': 'You can now chat and plan your session!',
        'discover.matchNone': 'No matches found',
        'discover.matchOne': 'Match 1 person',
        'discover.matchMany': 'Match {count} people',
        'discover.activityPickerTitle': 'Choose your activities',
        'discover.activityPickerHint': 'Pick at least one shared activity you want to connect and chat about',
        'matches.subtitle': 'People you matched with',
        'matches.loadError': "Couldn't load matches",
        'matches.emptyTitle': 'No matches yet',
        'matches.emptyHint': 'Keep swiping to find your activity partner!',
        'matches.goDiscover': 'Go to Discover',
        'matches.viewMatches': 'View matches',
        'matches.fallback': 'Match',
        'matches.directMessage': 'Direct message',
        'chat.fallbackTitle': 'Match Chat',
        'chat.emptyTitle': 'Say hi to your match!',
        'chat.emptyHint': 'Plan your activity session together',
        'chat.placeholder': 'Type a message...',
        'chat.menu': 'Options',
        'chat.unmatch': 'Remove match',
        'chat.unmatchTitle': 'Remove match?',
        'chat.unmatchHint': "This deletes the conversation and removes you both from each other's matches. This can't be undone.",
        'chat.unmatching': 'Removing...',
        'chat.report': 'Report user',
        'chat.reportTitle': 'Report user',
        'chat.reportHint': "Tell us what's going on. Our team will review it.",
        'chat.reportReasonHarassment': 'Harassment or abuse',
        'chat.reportReasonInappropriate': 'Inappropriate messages or photos',
        'chat.reportReasonFakeProfile': 'Fake profile',
        'chat.reportReasonSpam': 'Spam or scam',
        'chat.reportReasonOther': 'Other',
        'chat.reportDetailsPlaceholder': 'Add details (optional)',
        'chat.reportSubmit': 'Submit report',
        'chat.reporting': 'Submitting...',
        'chat.reportSuccess': "Report submitted. Thanks for letting us know.",
        'profile.edit': 'Edit',
        'profile.editTitle': 'Edit profile',
        'profile.share': 'Share',
        'profile.viewProfile': 'View profile',
        'premium.messageUpsellTitle': 'Direct messages are a Premium feature',
        'premium.messageUpsellHint': "Subscribe to FIT-M8 Premium to message anyone directly — no need to match first.",
        'premium.composeMessageTitle': 'Send a message',
        'premium.composeMessageHint': "This starts a match once you send it.",
        'profile.bio': 'Your bio...',
        'profile.signOut': 'Sign out',
        'profile.notFound': 'User not found',
        'profile.inCommon': 'In common',
        'profile.distanceAway': '{count} km away',
        'profile.addSport': 'Add an activity',
        'profile.allSports': "You've added every activity already!",
        'profile.addSportButton': 'Add activity',
        'profile.resetSwipes': 'Reset swipes',
        'profile.resettingSwipes': 'Resetting...',
        'profile.resetSwipesTitle': 'Reset swipes?',
        'profile.resetSwipesHint': "Previously liked or passed profiles will reappear in Discover. Your matches and conversations are kept.",
        'profile.discovery': 'Discovery',
        'profile.dangerZone': 'Danger zone',
        'profile.deleteAccount': 'Delete account',
        'profile.deletingAccount': 'Deleting...',
        'profile.deleteAccountTitle': 'Delete account?',
        'profile.deleteAccountHint': "This permanently deletes your profile, photos, swipes, matches and messages. This can't be undone.",
        'errors.requiresRecentLogin': 'Please sign out and sign back in, then try again.',
        'common.delete': 'Delete',
        'profile.statusTitle': 'Status',
        'profile.single': 'Single',
        'profile.trainer': 'Trainer',
        'appearance.title': 'Appearance',
        'appearance.light': 'Light',
        'appearance.dark': 'Dark',
        'appearance.appTheme': 'App Theme',
        'appearance.classic': 'Classic',
        'appearance.ocean': 'Ocean',
        'appearance.sunset': 'Sunset',
        'appearance.forest': 'Forest',
        'appearance.berry': 'Berry',
        'appearance.slate': 'Slate',
        'location.enterCity': 'Enter your city',
        'location.editCity': 'Edit city',
        'location.detecting': 'Detecting...',
        'location.useMyLocation': 'Use my location',
        'location.denied': 'Location access denied',
        'location.unsupported': "Geolocation isn't supported on this device",
        'location.detectFailed': "Couldn't detect your location",
        'location.resolveFailed': "Couldn't resolve your city",
        'location.outsideBarcelona': 'FIT-M8 is currently only available in Barcelona',
        'photo.chooseImage': 'Please choose an image file',
        'photo.uploadFailed': 'Upload failed',
        'activity.jogging': 'Jogging',
        'activity.padel': 'Padel',
        'activity.tennis': 'Tennis',
        'activity.beachvolley': 'Beach Volley',
        'activity.footvolley': 'Foot Volley',
        'activity.basketball': 'Basketball',
        'activity.soccer': 'Football',
        'activity.cycling': 'Cycling',
        'activity.swimming': 'Swimming',
        'activity.hiking': 'Hiking',
        'activity.pingpong': 'Ping Pong',
        'activity.pickleball': 'Pickleball',
        'activity.squash': 'Squash',
        'activity.frescobol': 'Frescobol',
        'activity.gym': 'Gym Training',
        'activity.calisthenics': 'Calisthenics',
        'activity.bodybuilding': 'Bodybuilding',
        'activity.crosstraining': 'Cross-training',
        'activity.functionalfitness': 'Functional Fitness',
        'activity.bootcamp': 'Bootcamp',
        'activity.yoga': 'Yoga',
        'activity.pilates': 'Pilates',
        'activity.meditation': 'Meditation',
        'activity.breathwork': 'Breathwork',
        'activity.rockclimbing': 'Rock Climbing',
        'activity.golf': 'Golf',
        'activity.boxing': 'Boxing',
        'activity.kickboxing': 'Kickboxing',
        'activity.muaythai': 'Muay Thai',
        'activity.karate': 'Karate',
        'activity.jiujitsu': 'Jiu-Jitsu',
        'activity.judo': 'Judo',
        'activity.mma': 'MMA',
        'activity.salsa': 'Salsa',
        'activity.bachata': 'Bachata',
        'activity.kizomba': 'Kizomba',
        'activity.barre': 'Barre',
        'activity.poledance': 'Pole Dance',
        'activity.trampoline': 'Trampolining',
        'activity.paddleboard': 'Paddleboard',
        'activity.kayak': 'Kayak',
        'activity.surf': 'Surfing',
        'activity.rollerblade': 'Rollerblading',
        'activity.skateboard': 'Skateboarding',
        'activityGroup.racquet': 'Racquet & Paddle Sports',
        'activityGroup.fitness': 'Fitness, Strength & Calisthenics',
        'activityGroup.ballSports': 'Ball & Team Sports',
        'activityGroup.wheelSkate': 'Wheel Mobility & Skate',
        'activityGroup.mindBody': 'Mind, Body & Recovery',
        'activityGroup.water': 'Board & Water Sports',
        'activityGroup.danceArts': 'Dance, Music & Performing Arts',
        'activityGroup.combat': 'Combat & Martial Arts',
        'common.other': 'Other',
        'format.all': 'All',
        'format.1v1': '1v1',
        'format.2v2': '2v2',
        'format.group': '4+',
        'skill.basic': 'Basic',
        'skill.medium': 'Medium',
        'skill.expert': 'Expert',
        'gender.male': 'Male',
        'gender.female': 'Female',
        'orientation.hetero': 'Hetero',
        'orientation.gay': 'Gay',
        'profile.addSports': 'Add {count} activities',
        'common.language': 'Language',
        'sports.maxHint': 'You can pick up to {max} activities',
        'sports.maxReached': "You've reached the {max}-activity limit",
        'sports.reorderHint': 'Drag to reorder — activities higher on the list rank you higher in Discover for that activity',
        'sports.orderInfoLabel': 'How activity order works',
        'sports.formatLevelInfoTitle': 'Format & level',
        'sports.formatLevelInfoBody': 'Format is the group size you play in for that activity (1v1, 2v2, or 4+), and level is your skill — both help us match you with the right people.',
        'common.dragToReorder': 'Drag to reorder',
        'premium.title': 'FIT-M8 Premium',
        'premium.subtitle': 'Unlock more from your FIT-M8 experience',
        'premium.priceLine': '$9.99 / month',
        'premium.featureMoreSportsTitle': 'Add more activities',
        'premium.featureMoreSportsHint': 'Up to {max} activities instead of {free} — more activities, more matches',
        'premium.featureDirectMessageTitle': 'Message anyone directly',
        'premium.featureDirectMessageHint': "Skip the match — reach out to any profile you're interested in",
        'premium.featureTrainerEventsTitle': 'Host events as a trainer',
        'premium.featureTrainerEventsHint': 'Create and promote sessions for people to join',
        'premium.comingSoon': 'Coming soon',
        'premium.subscribeButton': 'Subscribe now',
        'premium.inviteOnlyHint': 'Membership is invite-only right now — check back soon.',
        'premium.activeTitle': "You're Premium",
        'premium.activeHint': 'Thanks for supporting FIT-M8! Every premium feature is unlocked.',
        'premium.cancelButton': 'Cancel subscription',
        'profile.goPremium': 'Go Premium',
        'profile.premiumMember': 'Premium member',
        'profile.premiumFeature': 'Premium',
        'profile.socialLinks': 'Social links',
        'profile.socialLinksHint': 'Add links to your Instagram, WhatsApp, or other profiles',
        'profile.socialLinkPlaceholder': 'instagram.com/you',
        'profile.invalidSocialLink': 'Enter a valid link',
        'common.add': 'Add',
        'common.remove': 'Remove'
    },
    es: {
        'meta.description': 'Conecta con personas para hacer actividades cerca de ti', 'language.en': 'Inglés', 'language.es': 'Español', 'language.it': 'Italiano',
        'nav.discover': 'Descubrir', 'nav.matches': 'Coincidencias', 'nav.profile': 'Perfil', 'common.all': 'Todos', 'common.any': 'Cualquiera', 'common.search': 'Buscar', 'common.noResults': 'Sin resultados', 'common.showMore': 'Más +', 'common.save': 'Guardar', 'common.saving': 'Guardando...', 'common.refresh': 'Actualizar', 'common.close': 'Cerrar', 'common.back': 'Volver', 'common.loading': 'Cargando...', 'common.chat': 'Chat', 'common.match': 'Match', 'common.format': 'Formato', 'common.level': 'Nivel', 'common.gender': 'Género', 'common.orientation': 'Orientación', 'common.sports': 'Actividades', 'common.mySports': 'Mis actividades', 'common.noActivities': 'No hay actividades configuradas', 'common.profilePhoto': 'Foto de perfil', 'common.profilePhotoNumber': 'Foto de perfil {count}', 'common.removePhoto': 'Eliminar foto', 'common.previousPhoto': 'Foto anterior', 'common.nextPhoto': 'Foto siguiente', 'common.main': 'Principal', 'home.tagline': 'Encuentra tu compañero de actividad ideal.', 'home.taglineSecond': 'Desliza. Conecta. Juega.', 'home.allActivities': 'Todas las actividades', 'home.google': 'Continuar con Google', 'home.email': 'Continuar con email', 'home.signingIn': 'Iniciando sesión...', 'auth.welcome': 'Te damos la bienvenida', 'auth.join': 'Únete a FIT-M8', 'auth.loginSubtitle': 'Inicia sesión para encontrar tu próxima conexión', 'auth.registerSubtitle': 'Crea tu perfil de actividad', 'auth.or': 'o', 'auth.email': 'Correo electrónico', 'auth.password': 'Contraseña', 'auth.confirmPassword': 'Confirmar contraseña', 'auth.loading': 'Cargando...', 'auth.signIn': 'Iniciar sesión', 'auth.createAccount': 'Crear cuenta', 'auth.noAccount': '¿No tienes una cuenta?', 'auth.haveAccount': '¿Ya tienes una cuenta?', 'auth.signUp': 'Registrarse', 'auth.passwordMismatch': 'Las contraseñas no coinciden', 'errors.generic': 'Algo salió mal', 'onboarding.chooseLanguage': 'Elige tu idioma', 'onboarding.languageHint': 'Puedes cambiarlo más tarde en tus ajustes', 'onboarding.permissionsTitle': 'Mantente al día', 'onboarding.permissionsHint': 'Te pediremos un par de permisos para configurarlo todo', 'onboarding.notificationsTitle': 'Notificaciones push', 'onboarding.notificationsHint': 'Recibe avisos de nuevos matches y mensajes', 'onboarding.enableNotifications': 'Activar notificaciones', 'onboarding.notificationsEnabled': 'Notificaciones activadas', 'onboarding.notificationsBlocked': 'Bloqueadas — actívalas en los ajustes de tu navegador', 'onboarding.locationTitle': 'Ubicación', 'onboarding.locationHint': 'Se usa para encontrar compañeros de actividad cerca de ti', 'onboarding.aboutYou': 'Sobre ti', 'onboarding.aboutYouHint': 'Cuéntanos quién eres', 'onboarding.name': 'Tu nombre', 'onboarding.nameError': 'Introduce solo tu nombre', 'onboarding.bioOptional': 'Biografía breve (opcional)', 'onboarding.age': 'Edad', 'onboarding.birthdate': 'Fecha de nacimiento', 'onboarding.underageError': 'Debes tener al menos 18 años para usar FIT-M8', 'onboarding.yourSports': 'Tus actividades', 'onboarding.sportsHint': 'Elige las actividades que disfrutas', 'onboarding.selectAtLeastOneSport': 'Elige al menos una actividad para continuar', 'onboarding.yourSettings': 'Tus ajustes', 'onboarding.settingsHint': 'Elige formato y nivel para cada actividad', 'onboarding.profilePhotos': 'Fotos de perfil', 'onboarding.photosHint': 'Añade hasta 3 fotos para que otros puedan encontrarte. La primera será tu foto principal.', 'onboarding.photosRequired': 'Añade al menos una foto para continuar', 'onboarding.makeItYours': 'Últimos detalles', 'onboarding.appearanceHint': 'Configura tu ubicación, notificaciones y el estilo de la app', 'discover.filters': 'Filtros', 'discover.datingPreset': 'Citas', 'discover.friendsPreset': 'Amistad', 'discover.trainerPreset': 'Entrenador', 'discover.defaultPreset': 'Predeterminado', 'discover.titleDating': 'Citas', 'discover.titleFriends': 'Amistad', 'discover.titleTrainer': 'Entrenadores', 'discover.ageRange': 'Rango de edad', 'discover.distance': 'Distancia', 'discover.withinKm': 'A menos de {count} km', 'discover.noMorePlayers': 'No hay más jugadores', 'discover.matchTitle': '¡Es una coincidencia!', 'discover.matchHint': '¡Ahora pueden chatear y planear su sesión!', 'matches.subtitle': 'Personas con las que coincidiste', 'matches.loadError': 'No se pudieron cargar las coincidencias', 'matches.emptyTitle': 'Aún no hay coincidencias', 'matches.emptyHint': '¡Sigue deslizando para encontrar tu compañero de actividad!', 'matches.goDiscover': 'Ir a Descubrir', 'matches.fallback': 'Coincidencia', 'chat.fallbackTitle': 'Chat de coincidencia', 'chat.emptyTitle': '¡Saluda a tu coincidencia!', 'chat.emptyHint': 'Planifiquen juntos su actividad', 'chat.placeholder': 'Escribe un mensaje...', 'profile.edit': 'Editar', 'profile.editTitle': 'Editar perfil', 'profile.bio': 'Tu biografía...', 'profile.signOut': 'Cerrar sesión', 'profile.notFound': 'Usuario no encontrado', 'profile.inCommon': 'En común', 'profile.addSport': 'Añadir una actividad', 'profile.allSports': '¡Ya has añadido todas las actividades!', 'profile.addSportButton': 'Añadir actividad', 'profile.resetSwipes': 'Restablecer deslizes', 'profile.resettingSwipes': 'Restableciendo...', 'appearance.title': 'Apariencia', 'appearance.light': 'Claro', 'appearance.dark': 'Oscuro', 'appearance.appTheme': 'Tema de la aplicación', 'location.enterCity': 'Escribe tu ciudad', 'location.editCity': 'Editar ciudad', 'location.detecting': 'Detectando...', 'location.useMyLocation': 'Usar mi ubicación', 'location.denied': 'Acceso a la ubicación denegado', 'location.unsupported': 'La geolocalización no es compatible con este dispositivo', 'location.detectFailed': 'No se pudo detectar tu ubicación', 'location.resolveFailed': 'No se pudo encontrar tu ciudad', 'photo.chooseImage': 'Elige un archivo de imagen', 'photo.uploadFailed': 'No se pudo subir la imagen', 'activity.jogging': 'Correr', 'activity.padel': 'Pádel', 'activity.tennis': 'Tenis', 'activity.beachvolley': 'Vóley playa', 'activity.footvolley': 'Futevóley', 'activity.basketball': 'Baloncesto', 'activity.cycling': 'Ciclismo', 'activity.swimming': 'Natación', 'activity.hiking': 'Senderismo', 'activity.ping-pong': 'Ping-pong', 'activity.pickleball': 'Pickleball', 'activity.squash': 'Squash', 'activity.frescobol': 'Frescobol', 'activity.gym': 'Entrenamiento en gimnasio', 'activity.calisthenics': 'Calistenia', 'activity.bodybuilding': 'Culturismo', 'activity.crosstraining': 'Cross-training', 'activity.functionalfitness': 'Fitness funcional', 'activity.bootcamp': 'Bootcamp', 'activity.yoga': 'Yoga', 'activity.rockclimbing': 'Escalada', 'activity.golf': 'Golf', 'activity.paddleboard': 'Paddle surf', 'activity.surf': 'Surf', 'activity.rollerblade': 'Patinaje en línea', 'activity.skateboard': 'Monopatín', 'activity.soccer': 'Fútbol', 'format.all': 'Todos', 'format.1v1': '1 contra 1', 'format.2v2': '2 contra 2', 'format.group': '4+', 'skill.basic': 'Básico', 'skill.medium': 'Medio', 'skill.expert': 'Experto', 'gender.male': 'Hombre', 'gender.female': 'Mujer', 'orientation.hetero': 'Hetero', 'orientation.gay': 'Gay'
    },
    it: {
        'meta.description': 'Trova persone per fare attività vicino a te', 'language.en': 'Inglese', 'language.es': 'Spagnolo', 'language.it': 'Italiano',
        'nav.discover': 'Scopri', 'nav.matches': 'Match', 'nav.profile': 'Profilo', 'common.all': 'Tutti', 'common.any': 'Qualsiasi', 'common.search': 'Cerca', 'common.noResults': 'Nessun risultato', 'common.showMore': 'Altro +', 'common.save': 'Salva', 'common.saving': 'Salvataggio...', 'common.refresh': 'Aggiorna', 'common.close': 'Chiudi', 'common.back': 'Indietro', 'common.loading': 'Caricamento...', 'common.chat': 'Chat', 'common.match': 'Match', 'common.format': 'Formato', 'common.level': 'Livello', 'common.gender': 'Genere', 'common.orientation': 'Orientamento', 'common.sports': 'Attività', 'common.mySports': 'Le mie attività', 'common.noActivities': 'Nessuna attività impostata', 'common.profilePhoto': 'Foto profilo', 'common.profilePhotoNumber': 'Foto profilo {count}', 'common.removePhoto': 'Rimuovi foto', 'common.previousPhoto': 'Foto precedente', 'common.nextPhoto': 'Foto successiva', 'common.main': 'Principale', 'home.tagline': 'Trova il tuo compagno di attività ideale.', 'home.taglineSecond': 'Scorri. Abbina. Gioca.', 'home.allActivities': 'Tutte le attività', 'home.google': 'Continua con Google', 'home.email': 'Continua con email', 'home.signingIn': 'Accesso in corso...', 'auth.welcome': 'Bentornato', 'auth.join': 'Unisciti a FIT-M8', 'auth.loginSubtitle': 'Accedi per trovare il tuo prossimo match', 'auth.registerSubtitle': 'Crea il tuo profilo attività', 'auth.or': 'o', 'auth.email': 'Indirizzo email', 'auth.password': 'Password', 'auth.confirmPassword': 'Conferma password', 'auth.loading': 'Caricamento...', 'auth.signIn': 'Accedi', 'auth.createAccount': 'Crea account', 'auth.noAccount': 'Non hai un account?', 'auth.haveAccount': 'Hai già un account?', 'auth.signUp': 'Registrati', 'auth.passwordMismatch': 'Le password non corrispondono', 'errors.generic': 'Qualcosa è andato storto', 'onboarding.chooseLanguage': 'Scegli la tua lingua', 'onboarding.languageHint': 'Puoi cambiarlo più tardi nelle impostazioni', 'onboarding.permissionsTitle': 'Resta aggiornato', 'onboarding.permissionsHint': 'Ti chiederemo alcuni permessi per completare la configurazione', 'onboarding.notificationsTitle': 'Notifiche push', 'onboarding.notificationsHint': 'Ricevi avvisi per nuovi match e messaggi', 'onboarding.enableNotifications': 'Attiva notifiche', 'onboarding.notificationsEnabled': 'Notifiche attivate', 'onboarding.notificationsBlocked': 'Bloccate — attivale nelle impostazioni del tuo browser', 'onboarding.locationTitle': 'Posizione', 'onboarding.locationHint': 'Usata per trovare compagni di attività vicino a te', 'onboarding.aboutYou': 'Su di te', 'onboarding.aboutYouHint': 'Raccontaci chi sei', 'onboarding.name': 'Il tuo nome', 'onboarding.nameError': 'Inserisci solo il tuo nome', 'onboarding.bioOptional': 'Breve biografia (opzionale)', 'onboarding.age': 'Età', 'onboarding.birthdate': 'Data di nascita', 'onboarding.underageError': 'Devi avere almeno 18 anni per usare FIT-M8', 'onboarding.yourSports': 'Le tue attività', 'onboarding.sportsHint': 'Scegli le attività che ti piacciono', 'onboarding.selectAtLeastOneSport': 'Scegli almeno un\'attività per continuare', 'onboarding.yourSettings': 'Le tue impostazioni', 'onboarding.settingsHint': 'Scegli formato e livello per ogni attività', 'onboarding.profilePhotos': 'Foto profilo', 'onboarding.photosHint': 'Aggiungi fino a 3 foto per farti trovare dagli altri. La prima sarà quella principale.', 'onboarding.photosRequired': 'Aggiungi almeno una foto per continuare', 'onboarding.makeItYours': 'Ultimi ritocchi', 'onboarding.appearanceHint': 'Imposta la tua posizione, le notifiche e lo stile dell\'app', 'discover.filters': 'Filtri', 'discover.datingPreset': 'Incontri', 'discover.friendsPreset': 'Amicizia', 'discover.trainerPreset': 'Allenatore', 'discover.defaultPreset': 'Predefinito', 'discover.titleDating': 'Incontri', 'discover.titleFriends': 'Amicizia', 'discover.titleTrainer': 'Allenatori', 'discover.ageRange': 'Fascia d\'età', 'discover.distance': 'Distanza', 'discover.withinKm': 'Entro {count} km', 'discover.noMorePlayers': 'Nessun altro giocatore', 'discover.matchTitle': 'È un match!', 'discover.matchHint': 'Ora potete chattare e organizzare la sessione!', 'matches.subtitle': 'Persone con cui hai fatto match', 'matches.loadError': 'Impossibile caricare i match', 'matches.emptyTitle': 'Ancora nessun match', 'matches.emptyHint': 'Continua a scorrere per trovare il tuo compagno di attività!', 'matches.goDiscover': 'Vai a Scopri', 'matches.fallback': 'Match', 'chat.fallbackTitle': 'Chat del match', 'chat.emptyTitle': 'Saluta il tuo match!', 'chat.emptyHint': 'Organizzate insieme la vostra attività', 'chat.placeholder': 'Scrivi un messaggio...', 'profile.edit': 'Modifica', 'profile.editTitle': 'Modifica profilo', 'profile.bio': 'La tua biografia...', 'profile.signOut': 'Esci', 'profile.notFound': 'Utente non trovato', 'profile.inCommon': 'In comune', 'profile.addSport': 'Aggiungi un\'attività', 'profile.allSports': 'Hai già aggiunto tutte le attività!', 'profile.addSportButton': 'Aggiungi attività', 'profile.resetSwipes': 'Ripristina swipe', 'profile.resettingSwipes': 'Ripristino...', 'appearance.title': 'Aspetto', 'appearance.light': 'Chiaro', 'appearance.dark': 'Scuro', 'appearance.appTheme': 'Tema dell\'app', 'location.enterCity': 'Inserisci la tua città', 'location.editCity': 'Modifica città', 'location.detecting': 'Rilevamento...', 'location.useMyLocation': 'Usa la mia posizione', 'location.denied': 'Accesso alla posizione negato', 'location.unsupported': 'La geolocalizzazione non è supportata su questo dispositivo', 'location.detectFailed': 'Impossibile rilevare la tua posizione', 'location.resolveFailed': 'Impossibile trovare la tua città', 'photo.chooseImage': 'Scegli un file immagine', 'photo.uploadFailed': 'Impossibile caricare l\'immagine', 'activity.jogging': 'Corsa', 'activity.padel': 'Padel', 'activity.tennis': 'Tennis', 'activity.beachvolley': 'Beach volley', 'activity.footvolley': 'Footvolley', 'activity.basketball': 'Pallacanestro', 'activity.cycling': 'Ciclismo', 'activity.swimming': 'Nuoto', 'activity.hiking': 'Escursionismo', 'activity.ping-pong': 'Ping pong', 'activity.pickleball': 'Pickleball', 'activity.squash': 'Squash', 'activity.frescobol': 'Frescobol', 'activity.gym': 'Allenamento in palestra', 'activity.calisthenics': 'Calistenia', 'activity.bodybuilding': 'Bodybuilding', 'activity.crosstraining': 'Cross-training', 'activity.functionalfitness': 'Fitness funzionale', 'activity.bootcamp': 'Bootcamp', 'activity.yoga': 'Yoga', 'activity.rockclimbing': 'Arrampicata', 'activity.golf': 'Golf', 'activity.paddleboard': 'Paddleboard', 'activity.surf': 'Surf', 'activity.rollerblade': 'Pattini in linea', 'activity.skateboard': 'Skateboard', 'activity.soccer': 'Calcio', 'format.all': 'Tutti', 'format.1v1': '1 contro 1', 'format.2v2': '2 contro 2', 'format.group': '4+', 'skill.basic': 'Base', 'skill.medium': 'Medio', 'skill.expert': 'Esperto', 'gender.male': 'Uomo', 'gender.female': 'Donna', 'orientation.hetero': 'Etero', 'orientation.gay': 'Gay'
    }
} as const;

export type TranslationKey = keyof typeof MESSAGES.en;
export type TranslationParams = Record<string, string | number>;

const EXTRA_MESSAGES: Record<LanguageCode, Partial<Record<TranslationKey, string>>> = {
    en: {},
    es: {
        'home.howItWorksTitle': 'Cómo funciona FIT-M8',
        'home.step1Title': 'Crea tu perfil',
        'home.step1Desc': 'Elige los deportes y actividades que te gustan y configura tu ubicación.',
        'home.stepFiltersTitle': 'Afina tus coincidencias',
        'home.stepFiltersDesc': 'Filtra por edad, distancia, actividades y más para encontrar exactamente a quien buscas.',
        'home.step2Title': 'Descubre gente cercana',
        'home.step2Desc': 'Desliza entre personas que comparten tus actividades cerca de ti.',
        'home.step3Title': 'Conecta y juega',
        'home.step3Desc': 'Chatea, organiza una sesión y quedad para jugar juntos.',
        'home.activitiesTitle': 'Encuentra compañero para',
        'home.peopleInterested': 'personas interesadas',
        'home.activitiesIntroTitle': 'Match por actividades compartidas',
        'home.activitiesIntroBody': 'Añade los deportes y actividades que te gustan: cuantos más añadas, con más gente podrás conectar.',
        'home.activitiesOrderTitle': 'El orden marca tu prioridad',
        'home.activitiesOrderBody': 'El orden de tu lista de actividades es tu prioridad, así que pon tus favoritas primero para mejores coincidencias.',
        'home.followUs': 'Síguenos',
        'home.rights': 'Todos los derechos reservados.',
        'common.yes': 'Sí',
        'common.no': 'No',
        'common.other': 'Otros',
        'activityGroup.racquet': 'Raqueta y Pádel',
        'activityGroup.fitness': 'Fitness, Fuerza y Calistenia',
        'activityGroup.ballSports': 'Deportes de Pelota y Equipo',
        'activityGroup.wheelSkate': 'Ruedas y Skate',
        'activityGroup.mindBody': 'Mente, Cuerpo y Recuperación',
        'activityGroup.water': 'Deportes de Tabla y Agua',
        'activityGroup.danceArts': 'Danza, Música y Artes Escénicas',
        'activityGroup.combat': 'Combate y Artes Marciales',
        'activity.pilates': 'Pilates',
        'activity.meditation': 'Meditación',
        'activity.breathwork': 'Trabajo de Respiración',
        'activity.salsa': 'Salsa',
        'activity.bachata': 'Bachata',
        'activity.kizomba': 'Kizomba',
        'activity.barre': 'Barre',
        'activity.poledance': 'Pole Dance',
        'activity.trampoline': 'Trampolín',
        'activity.kayak': 'Kayak',
        'activity.boxing': 'Boxeo',
        'activity.kickboxing': 'Kickboxing',
        'activity.muaythai': 'Muay Thai',
        'activity.karate': 'Karate',
        'activity.jiujitsu': 'Jiu-Jitsu',
        'activity.judo': 'Judo',
        'activity.mma': 'MMA',
        'discover.presetHintToggle': '¿Citas, amistad o entrenador?',
        'discover.presetHintSubtitle': 'Descubre qué ajusta cada filtro rápido.',
        'discover.presetHintPickOne': 'Elige una opción para continuar',
        'discover.presetHintDefaultBody': 'Borra todos los filtros para ver todas las actividades, edades y distancias, sin filtros de citas.',
        'discover.presetHintDatingBody': 'Configura los filtros de género y orientación para conocer a personas con las que conectes.',
        'discover.presetHintFriendsBody': 'Desactiva los filtros de citas y busca compañeros de entrenamiento para compartir una sesión.',
        'discover.presetHintTrainerBody': 'Filtra por nivel Experto para encontrar jugadores y entrenadores con experiencia que te ayuden a mejorar.',
        'location.outsideBarcelona': 'FIT-M8 solo está disponible en Barcelona por ahora',
        'auth.forgotPassword': '¿Olvidaste tu contraseña?',
        'auth.enterEmailFirst': 'Introduce primero tu correo electrónico',
        'auth.resetEmailSent': 'Correo de restablecimiento enviado. Revisa tu bandeja de entrada.',
        'auth.verifyEmailTitle': 'Verifica tu correo electrónico',
        'auth.verifyEmailHint': 'Hemos enviado un enlace de verificación a {email}. Confírmalo para empezar a aparecer en Descubrir.',
        'auth.resendVerification': 'Reenviar correo de verificación',
        'auth.verificationEmailSent': 'Correo de verificación enviado. Revisa tu bandeja de entrada.',
        'auth.iHaveVerified': 'Ya he verificado mi correo',
        'auth.stillNotVerified': 'Todavía no está verificado. Revisa tu bandeja de entrada (y spam).',
        'auth.errorEmailInUse': 'Ya existe una cuenta con este correo. Intenta iniciar sesión.',
        'auth.errorInvalidEmail': 'Introduce un correo electrónico válido.',
        'auth.errorWeakPassword': 'Elige una contraseña más segura (al menos 6 caracteres).',
        'auth.errorInvalidCredential': 'Correo o contraseña incorrectos.',
        'auth.errorTooManyRequests': 'Demasiados intentos. Espera un momento e intenta de nuevo.',
        'auth.emailVerifiedSuccess': '¡Tu correo electrónico ha sido verificado!',
        'onboarding.howItWorks': 'Cómo funciona',
        'onboarding.howItWorksHint': 'Tus filtros deciden a quién conoces',
        'discover.matchNone': 'Ningún resultado',
        'discover.matchOne': 'Conectar con 1 persona',
        'discover.matchMany': 'Conectar con {count} personas',
        'discover.activityPickerTitle': 'Elige tus actividades',
        'discover.activityPickerHint': 'Selecciona al menos una actividad en común para conectar y chatear',
        'profile.distanceAway': 'A {count} km',
        'intro.skip': 'Omitir',
        'intro.next': 'Siguiente',
        'intro.dating.title': 'Encuentra una cita',
        'intro.dating.body': 'Configura tus filtros de género y orientación para conocer a personas con las que conectes mientras practicas las actividades que te gustan.',
        'intro.friends.title': 'Haz nuevos amigos',
        'intro.friends.body': '¿No buscas una cita? Desactiva los filtros y encuentra compañeros de entrenamiento para compartir una sesión.',
        'intro.experts.title': 'Aprende de expertos',
        'intro.experts.body': 'Filtra por nivel Experto para encontrar jugadores y entrenadores con experiencia que te ayuden a mejorar tu juego.',
        'common.language': 'Idioma',
        'common.name': 'Nombre',
        'common.email': 'Correo electrónico',
        'common.biography': 'Biografía',
        'common.location': 'Ubicación',
        'discover.singleFilter': 'Soltero/a',
        'discover.trainerFilter': 'Entrenador/a',
        'profile.statusTitle': 'Estado',
        'profile.single': 'Soltero/a',
        'profile.trainer': 'Entrenador/a',
        'common.message': 'Mensaje',
        'common.send': 'Enviar',
        'common.sending': 'Enviando...',
        'common.gotIt': 'Entendido',
        'common.maybeLater': 'Quizás más tarde',
        'common.undo': 'Deshacer',
        'profile.share': 'Compartir', 'profile.viewProfile': 'Ver perfil',
        'premium.messageUpsellTitle': 'Los mensajes directos son una función Premium',
        'premium.messageUpsellHint': 'Suscríbete a FIT-M8 Premium para escribir directamente a cualquier persona, sin necesidad de hacer match antes.',
        'premium.composeMessageTitle': 'Envía un mensaje',
        'premium.composeMessageHint': 'Esto crea un match en cuanto lo envíes.',
        'profile.resetSwipesTitle': '¿Restablecer desplazamientos?',
        'profile.resetSwipesHint': 'Los perfiles que ya has valorado volverán a aparecer en Descubrir. Tus coincidencias y conversaciones se conservan.',
        'profile.dangerZone': 'Zona de peligro',
        'profile.deleteAccount': 'Eliminar cuenta',
        'profile.deletingAccount': 'Eliminando...',
        'profile.deleteAccountTitle': '¿Eliminar cuenta?',
        'profile.deleteAccountHint': 'Esto elimina permanentemente tu perfil, fotos, deslizamientos, coincidencias y mensajes. Esta acción no se puede deshacer.',
        'errors.requiresRecentLogin': 'Por seguridad, cierra sesión y vuelve a iniciar sesión antes de continuar.',
        'common.delete': 'Eliminar',
        'sports.maxHint': 'Puedes elegir hasta {max} actividades',
        'sports.maxReached': 'Has alcanzado el límite de {max} actividades',
        'sports.reorderHint': 'Arrastra para reordenar: las actividades más arriba te dan más prioridad en Descubrir para esa actividad',
        'sports.orderInfoLabel': 'Cómo funciona el orden de actividades',
        'sports.formatLevelInfoTitle': 'Formato y nivel',
        'sports.formatLevelInfoBody': 'El formato es el tamaño de grupo con el que juegas esa actividad (1v1, 2v2 o 4+), y el nivel es tu habilidad; ambos nos ayudan a encontrarte a las personas adecuadas.',
        'common.dragToReorder': 'Arrastra para reordenar',
        'premium.title': 'FIT-M8 Premium',
        'premium.subtitle': 'Desbloquea más funciones de FIT-M8',
        'premium.priceLine': '9,99 $ / mes',
        'premium.featureMoreSportsTitle': 'Añade más actividades',
        'premium.featureMoreSportsHint': 'Hasta {max} actividades en lugar de {free} — más actividades, más matches',
        'premium.featureDirectMessageTitle': 'Escribe directamente a cualquiera',
        'premium.featureDirectMessageHint': 'Sin esperar a hacer match: contacta con cualquier perfil que te interese',
        'premium.featureTrainerEventsTitle': 'Organiza eventos como entrenador',
        'premium.featureTrainerEventsHint': 'Crea y promociona sesiones para que la gente se apunte',
        'premium.comingSoon': 'Próximamente',
        'premium.subscribeButton': 'Suscribirme ahora',
        'premium.inviteOnlyHint': 'La membresía es solo por invitación por ahora — vuelve pronto.',
        'premium.activeTitle': 'Ya eres Premium',
        'premium.activeHint': '¡Gracias por apoyar a FIT-M8! Todas las funciones premium están desbloqueadas.',
        'premium.cancelButton': 'Cancelar suscripción',
        'profile.goPremium': 'Hazte Premium',
        'profile.premiumMember': 'Miembro Premium',
        'profile.premiumFeature': 'Premium',
        'common.keepSwiping': 'Seguir deslizando',
        'matches.viewMatches': 'Ver coincidencias',
        'chat.menu': 'Opciones',
        'chat.unmatch': 'Eliminar coincidencia',
        'chat.unmatchTitle': '¿Eliminar coincidencia?',
        'chat.unmatchHint': 'Esto elimina la conversación y os quita de las coincidencias mutuas. Esta acción no se puede deshacer.',
        'chat.unmatching': 'Eliminando...',
        'chat.report': 'Denunciar usuario',
        'chat.reportTitle': 'Denunciar usuario',
        'chat.reportHint': 'Cuéntanos qué está pasando. Nuestro equipo lo revisará.',
        'chat.reportReasonHarassment': 'Acoso o abuso',
        'chat.reportReasonInappropriate': 'Mensajes o fotos inapropiadas',
        'chat.reportReasonFakeProfile': 'Perfil falso',
        'chat.reportReasonSpam': 'Spam o estafa',
        'chat.reportReasonOther': 'Otro',
        'chat.reportDetailsPlaceholder': 'Añade detalles (opcional)',
        'chat.reportSubmit': 'Enviar denuncia',
        'chat.reporting': 'Enviando...',
        'chat.reportSuccess': 'Denuncia enviada. Gracias por avisarnos.',
        'profile.socialLinks': 'Redes sociales',
        'profile.socialLinksHint': 'Añade enlaces a tu Instagram, WhatsApp u otros perfiles',
        'profile.socialLinkPlaceholder': 'instagram.com/tu_usuario',
        'profile.invalidSocialLink': 'Introduce un enlace válido',
        'common.add': 'Añadir',
        'common.remove': 'Eliminar'
    },
    it: {
        'home.howItWorksTitle': 'Come funziona FIT-M8',
        'home.step1Title': 'Crea il tuo profilo',
        'home.step1Desc': 'Scegli gli sport e le attività che ami e imposta la tua posizione.',
        'home.stepFiltersTitle': 'Perfeziona i tuoi match',
        'home.stepFiltersDesc': 'Filtra per età, distanza, attività e altro per trovare esattamente chi cerchi.',
        'home.step2Title': 'Scopri persone vicine',
        'home.step2Desc': 'Scorri tra le persone che condividono le tue attività vicino a te.',
        'home.step3Title': 'Fai match e gioca',
        'home.step3Desc': 'Chatta, organizza una sessione e incontratevi per giocare insieme.',
        'home.activitiesTitle': 'Trova un compagno per',
        'home.peopleInterested': 'persone interessate',
        'home.activitiesIntroTitle': 'Match in base alle attività condivise',
        'home.activitiesIntroBody': 'Aggiungi gli sport e le attività che ami: più ne aggiungi, più persone potrai incontrare.',
        'home.activitiesOrderTitle': "L'ordine indica la tua priorità",
        'home.activitiesOrderBody': "L'ordine della tua lista di attività è la tua priorità: metti le preferite in cima per match migliori.",
        'home.followUs': 'Seguici',
        'home.rights': 'Tutti i diritti riservati.',
        'common.yes': 'Sì',
        'common.no': 'No',
        'auth.forgotPassword': 'Hai dimenticato la password?',
        'auth.enterEmailFirst': 'Inserisci prima il tuo indirizzo email',
        'auth.resetEmailSent': 'Email di reimpostazione inviata. Controlla la tua posta in arrivo.',
        'auth.verifyEmailTitle': 'Verifica la tua email',
        'auth.verifyEmailHint': 'Abbiamo inviato un link di verifica a {email}. Confermalo per iniziare ad apparire in Scopri.',
        'auth.resendVerification': 'Invia di nuovo l\'email di verifica',
        'auth.verificationEmailSent': 'Email di verifica inviata. Controlla la tua posta in arrivo.',
        'auth.iHaveVerified': 'Ho già verificato la mia email',
        'auth.stillNotVerified': 'Non ancora verificata. Controlla la posta in arrivo (e lo spam).',
        'auth.errorEmailInUse': 'Esiste già un account con questa email. Prova ad accedere.',
        'auth.errorInvalidEmail': 'Inserisci un indirizzo email valido.',
        'auth.errorWeakPassword': 'Scegli una password più sicura (almeno 6 caratteri).',
        'auth.errorInvalidCredential': 'Email o password errati.',
        'auth.errorTooManyRequests': 'Troppi tentativi. Attendi un momento e riprova.',
        'auth.emailVerifiedSuccess': 'La tua email è stata verificata!',
        'onboarding.howItWorks': 'Come funziona',
        'onboarding.howItWorksHint': 'I tuoi filtri decidono chi incontri',
        'discover.matchNone': 'Nessun risultato',
        'discover.matchOne': 'Connettiti con 1 persona',
        'discover.matchMany': 'Connettiti con {count} persone',
        'discover.activityPickerTitle': 'Scegli le tue attività',
        'discover.activityPickerHint': 'Seleziona almeno un\'attività in comune per connetterti e chattare',
        'profile.distanceAway': 'A {count} km',
        'intro.skip': 'Salta',
        'intro.next': 'Avanti',
        'intro.dating.title': 'Trova un appuntamento',
        'intro.dating.body': 'Imposta i filtri di genere e orientamento per conoscere persone con cui puoi entrare in sintonia mentre pratichi le tue attività preferite.',
        'intro.friends.title': 'Fai nuovi amici',
        'intro.friends.body': 'Non cerchi appuntamenti? Disattiva i filtri e trova compagni di allenamento con cui condividere una sessione.',
        'intro.experts.title': 'Impara dagli esperti',
        'intro.experts.body': 'Filtra per livello Esperto per trovare giocatori e allenatori esperti che possono aiutarti a migliorare il tuo gioco.',
        'common.language': 'Lingua',
        'common.name': 'Nome',
        'common.email': 'Email',
        'common.biography': 'Biografia',
        'common.location': 'Posizione',
        'common.message': 'Messaggio',
        'common.send': 'Invia',
        'common.sending': 'Invio...',
        'common.gotIt': 'Capito',
        'common.maybeLater': 'Magari più tardi',
        'common.undo': 'Annulla',
        'profile.share': 'Condividi', 'profile.viewProfile': 'Vedi profilo',
        'premium.messageUpsellTitle': 'I messaggi diretti sono una funzione Premium',
        'premium.messageUpsellHint': 'Abbonati a FIT-M8 Premium per scrivere direttamente a chiunque, senza dover fare prima match.',
        'premium.composeMessageTitle': 'Invia un messaggio',
        'premium.composeMessageHint': 'Questo crea un match non appena lo invii.',
        'profile.resetSwipesTitle': 'Ripristinare gli swipe?',
        'profile.resetSwipesHint': 'I profili già valutati riappariranno in Scopri. I tuoi match e le conversazioni vengono mantenuti.',
        'profile.dangerZone': 'Zona pericolosa',
        'profile.deleteAccount': 'Elimina account',
        'profile.deletingAccount': 'Eliminazione...',
        'profile.deleteAccountTitle': 'Eliminare l\'account?',
        'profile.deleteAccountHint': 'Questo elimina definitivamente il tuo profilo, foto, swipe, match e messaggi. Questa azione non può essere annullata.',
        'errors.requiresRecentLogin': 'Per motivi di sicurezza, esci e accedi di nuovo prima di continuare.',
        'common.delete': 'Elimina',
        'sports.maxHint': 'Puoi scegliere fino a {max} attività',
        'sports.maxReached': 'Hai raggiunto il limite di {max} attività',
        'sports.reorderHint': 'Trascina per riordinare: le attività più in alto ti danno più priorità in Scopri per quell\'attività',
        'sports.orderInfoLabel': "Come funziona l'ordine delle attività",
        'sports.formatLevelInfoTitle': 'Formato e livello',
        'sports.formatLevelInfoBody': "Il formato è la dimensione del gruppo con cui giochi quell'attività (1v1, 2v2 o 4+), e il livello è la tua abilità: entrambi ci aiutano a trovarti le persone giuste.",
        'common.dragToReorder': 'Trascina per riordinare',
        'premium.title': 'FIT-M8 Premium',
        'premium.subtitle': 'Sblocca più funzionalità di FIT-M8',
        'premium.priceLine': '9,99 $ / mese',
        'premium.featureMoreSportsTitle': 'Aggiungi più attività',
        'premium.featureMoreSportsHint': 'Fino a {max} attività invece di {free} — più attività, più match',
        'premium.featureDirectMessageTitle': 'Invia messaggi diretti a chiunque',
        'premium.featureDirectMessageHint': 'Senza aspettare un match: contatta qualsiasi profilo ti interessi',
        'premium.featureTrainerEventsTitle': 'Organizza eventi come allenatore',
        'premium.featureTrainerEventsHint': 'Crea e promuovi sessioni a cui le persone possono partecipare',
        'premium.comingSoon': 'Prossimamente',
        'premium.subscribeButton': 'Abbonati ora',
        'premium.inviteOnlyHint': 'L\'iscrizione è al momento solo su invito — torna presto a controllare.',
        'premium.activeTitle': 'Sei già Premium',
        'premium.activeHint': 'Grazie per il tuo supporto a FIT-M8! Tutte le funzionalità premium sono sbloccate.',
        'premium.cancelButton': 'Annulla abbonamento',
        'profile.goPremium': 'Passa a Premium',
        'profile.premiumMember': 'Membro Premium',
        'profile.premiumFeature': 'Premium',
        'common.keepSwiping': 'Continua a scorrere',
        'matches.viewMatches': 'Vedi i match',
        'chat.menu': 'Opzioni',
        'chat.unmatch': 'Rimuovi match',
        'chat.unmatchTitle': 'Rimuovere il match?',
        'chat.unmatchHint': 'Questo elimina la conversazione e vi rimuove reciprocamente dai match. Questa azione non può essere annullata.',
        'chat.unmatching': 'Rimozione...',
        'chat.report': 'Segnala utente',
        'chat.reportTitle': 'Segnala utente',
        'chat.reportHint': 'Raccontaci cosa succede. Il nostro team esaminerà la segnalazione.',
        'chat.reportReasonHarassment': 'Molestie o abusi',
        'chat.reportReasonInappropriate': 'Messaggi o foto inappropriati',
        'chat.reportReasonFakeProfile': 'Profilo falso',
        'chat.reportReasonSpam': 'Spam o truffa',
        'chat.reportReasonOther': 'Altro',
        'chat.reportDetailsPlaceholder': 'Aggiungi dettagli (facoltativo)',
        'chat.reportSubmit': 'Invia segnalazione',
        'chat.reporting': 'Invio...',
        'chat.reportSuccess': 'Segnalazione inviata. Grazie per averci avvisato.',
        'profile.socialLinks': 'Social',
        'profile.socialLinksHint': 'Aggiungi link al tuo Instagram, WhatsApp o altri profili',
        'profile.socialLinkPlaceholder': 'instagram.com/tuo-utente',
        'profile.invalidSocialLink': 'Inserisci un link valido',
        'common.add': 'Aggiungi',
        'common.remove': 'Rimuovi',
        'discover.presetHintToggle': 'Incontri, amicizia o allenatore?',
        'discover.presetHintSubtitle': 'Scopri cosa regola ogni filtro rapido.',
        'discover.presetHintPickOne': 'Scegli un\'opzione per continuare',
        'discover.presetHintDefaultBody': 'Cancella tutti i filtri per vedere tutte le attività, età e distanze, senza filtri per gli incontri.',
        'discover.presetHintDatingBody': 'Imposta i filtri di genere e orientamento per conoscere persone con cui potresti entrare in sintonia.',
        'discover.presetHintFriendsBody': 'Disattiva i filtri per gli incontri e trova compagni di allenamento con cui condividere una sessione.',
        'discover.presetHintTrainerBody': 'Filtra per livello Esperto per trovare giocatori e allenatori esperti che ti aiutino a migliorare.',
        'location.outsideBarcelona': 'FIT-M8 al momento è disponibile solo a Barcellona',
        'common.other': 'Altro',
        'activityGroup.racquet': 'Racchetta e Padel',
        'activityGroup.fitness': 'Fitness, Forza e Calistenia',
        'activityGroup.ballSports': 'Sport di Squadra e con la Palla',
        'activityGroup.wheelSkate': 'Ruote e Skate',
        'activityGroup.mindBody': 'Mente, Corpo e Recupero',
        'activityGroup.water': 'Sport da Tavola e Acquatici',
        'activityGroup.danceArts': 'Danza, Musica e Arti Performative',
        'activityGroup.combat': 'Combattimento e Arti Marziali',
        'activity.pilates': 'Pilates',
        'activity.meditation': 'Meditazione',
        'activity.breathwork': 'Respirazione',
        'activity.salsa': 'Salsa',
        'activity.bachata': 'Bachata',
        'activity.kizomba': 'Kizomba',
        'activity.barre': 'Barre',
        'activity.poledance': 'Pole Dance',
        'activity.trampoline': 'Trampolino',
        'activity.kayak': 'Kayak',
        'activity.boxing': 'Boxe',
        'activity.kickboxing': 'Kickboxing',
        'activity.muaythai': 'Muay Thai',
        'activity.karate': 'Karate',
        'activity.jiujitsu': 'Jiu-Jitsu',
        'activity.judo': 'Judo',
        'activity.mma': 'MMA'
    }
};

export interface Translator {
    t: (key: TranslationKey, params?: TranslationParams) => string;
    activity: (id: string) => string;
    activityGroup: (id: string) => string;
    format: (value: string) => string;
    skill: (value: string) => string;
    gender: (value: string) => string;
    orientation: (value: string) => string;
}

export function createTranslator(language: LanguageCode): Translator {
    const messages: Partial<Record<TranslationKey, string>> = {
        ...MESSAGES[language],
        ...EXTRA_MESSAGES[language]
    };
    const t = (key: TranslationKey, params: TranslationParams = {}) => {
        const template = messages[key] ?? MESSAGES.en[key] ?? key;
        return template.replace(/\{(\w+)\}/g, (_match: string, name: string) => String(params[name] ?? `{${name}}`));
    };
    const normalizeEnumValue = (value: string) => {
        const normalized = String(value ?? '').trim().toLowerCase();
        if (normalized === 'straight' || normalized === 'Hetero') return 'hetero';
        if (normalized === 'male' || normalized === 'female' || normalized === 'basic' || normalized === 'expert') return normalized;
        return normalized;
    };
    const humanize = (value: string) =>
        String(value ?? '')
            .replace(/([a-z])([A-Z])/g, '$1 $2')
            .split(/[-_\s]+/)
            .filter(Boolean)
            .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
            .join(' ');
    const label = (prefix: string, value: string) => {
        const key = `${prefix}.${normalizeEnumValue(value)}` as TranslationKey;
        const translated = t(key);
        return translated === key ? humanize(normalizeEnumValue(value)) : translated;
    };
    // activity.* keys are always lowercase-concatenated regardless of the ActivityId's casing
    const activityLabel = (id: string) => {
        const key = `activity.${String(id ?? '').trim().toLowerCase()}` as TranslationKey;
        const translated = t(key);
        return translated === key ? humanize(id) : translated;
    };
    const activityGroupLabel = (id: string) => {
        const key = `activityGroup.${String(id ?? '').trim()}` as TranslationKey;
        const translated = t(key);
        return translated === key ? humanize(id) : translated;
    };

    return {
        t,
        activity: activityLabel,
        activityGroup: activityGroupLabel,
        format: (value) => value === '1v1' || value === '2v2' ? value : label('format', value),
        skill: (value) => label('skill', value),
        gender: (value) => label('gender', value),
        orientation: (value) => label('orientation', value)
    };
}

const LANGUAGE_KEY = 'fit-m8-language';
const DEFAULT_LANGUAGE: LanguageCode = 'en';

function browserLanguage(): LanguageCode {
    if (typeof navigator === 'undefined') return DEFAULT_LANGUAGE;
    const language = navigator.language.toLowerCase().split('-')[0];
    return LANGUAGES.some((option) => option.code === language)
        ? (language as LanguageCode)
        : DEFAULT_LANGUAGE;
}

function applyLanguage(language: LanguageCode) {
    if (typeof document !== 'undefined') document.documentElement.lang = language;
}

function createLanguageStore() {
    const { subscribe, set } = writable<LanguageCode>(DEFAULT_LANGUAGE);

    return {
        subscribe,
        init: () => {
            if (typeof window === 'undefined') return;
            const savedLanguage = window.localStorage.getItem(LANGUAGE_KEY);
            const language = LANGUAGES.some((option) => option.code === savedLanguage)
                ? (savedLanguage as LanguageCode)
                : browserLanguage();
            applyLanguage(language);
            set(language);
        },
        selectLanguage: (language: LanguageCode) => {
            if (!LANGUAGES.some((option) => option.code === language)) return;
            applyLanguage(language);
            if (typeof window !== 'undefined') window.localStorage.setItem(LANGUAGE_KEY, language);
            set(language);
        },
        // Clears the saved preference and reverts to the browser/default language, e.g. after account deletion.
        reset: () => {
            if (typeof window !== 'undefined') window.localStorage.removeItem(LANGUAGE_KEY);
            const language = browserLanguage();
            applyLanguage(language);
            set(language);
        }
    };
}

export const activeLanguage = createLanguageStore();
